### ISSUE TITLE
flutter web debug, only a blank page in chrome

### ISSUE THREAD

**Issue by what2003** [dart-lang/webdev#1090]
Flutter run -d chrome or debug, only a blank page in chrome, tried flutter upgrade, flutter pub cache repair, flutter clean, nothing worked. Please help!

**vs code debug console**:
Launching lib/main.dart on Chrome in debug mode...

╰─$ flutter doctor -v          
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.22.0-1.0.pre at /Users/jack/flutter
    • Framework revision ce40de69b7 (10 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.8 dev

• No issues found!

**chrome console**:
client.js:3282 Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://localhost:55454/dwds/src/injected/client.js:3495:43)
    at http://localhost:55454/dwds/src/injected/client.js:22811:60
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:55454/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:55454/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:55454/dwds/src/injected/client.js:3757:20)
    at RequireRestarter._getDigests$0 (http://localhost:55454/dwds/src/injected/client.js:22823:16)
    at http://localhost:55454/dwds/src/injected/client.js:22838:48
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:55454/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:55454/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:55454/dwds/src/injected/client.js:3757:20)
    at RequireRestarter._initialize$0 (http://localhost:55454/dwds/src/injected/client.js:22846:16)
    at http://localhost:55454/dwds/src/injected/client.js:8578:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:55454/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:55454/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:55454/dwds/src/injected/client.js:3757:20)
    at Object.RequireRestarter_create (http://localhost:55454/dwds/src/injected/client.js:8590:16)
    at http://localhost:55454/dwds/src/injected/client.js:22398:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:55454/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:55454/dwds/src/injected/client.js:11010:12)
    at _awaitOnObject_closure.call$1 (http://localhost:55454/dwds/src/injected/client.js:10996:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:55454/dwds/src/injected/client.js:4118:18)
    at _CustomZone.runUnary$2$2 (http://localhost:55454/dwds/src/injected/client.js:12315:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:55454/dwds/src/injected/client.js:11376:51)
    at Object._Future__propagateToListeners (http://localhost:55454/dwds/src/injected/client.js:3905:93)
    at _Future._complete$1 (http://localhost:55454/dwds/src/injected/client.js:11200:11)
    at Object._cancelAndValue (http://localhost:55454/dwds/src/injected/client.js:4060:16)
    at Stream_first_closure0.call$1 (http://localhost:55454/dwds/src/injected/client.js:11468:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://localhost:55454/dwds/src/injected/client.js:17396:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:55454/dwds/src/injected/client.js:4124:16)
    at _CustomZone.runUnary$2$2 (http://localhost:55454/dwds/src/injected/client.js:12315:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:55454/dwds/src/injected/client.js:12247:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:55454/dwds/src/injected/client.js:12450:25)
    at invokeClosure (http://localhost:55454/dwds/src/injected/client.js:1204:26)
    at EventSource.<anonymous> (http://localhost:55454/dwds/src/injected/client.js:1223:18)

**Comment by what2003** [comment]
never mind, I change chrome from verson86 to 85, problem gone!
hope this helps others who has the same issue.
