### ISSUE TITLE
Investigate disappearing directory issue during expression compiler initialization.

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1282]
We encounter an intermittent failure during debugging applications in google3:

```
[SEVERE] ExpressionCompilerService: Starting...
Unhandled exception:
FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      _Directory.current (dart:io/directory_impl.dart:42:7)
#1      Directory.current (dart:io/directory.dart:136:25)
#2      _Compiler.start (package:dwds/src/services/expression_compiler_service.dart:112:45)
#3      ExpressionCompilerService.initialize (package:dwds/src/services/expression_compiler_service.dart:303:36)
<asynchronous suspension>
#4      ChromeProxyService.updateCompilerDependencies (package:dwds/src/services/chrome_proxy_service.dart:180:7)
<asynchronous suspension>
```

See the PR mentioned below for description and a repro (reverting the change and trying to debug an ACX demo will reproduce the problem almost every time).

We should create a smaller repro and find and fix the underlying problem.

**Comment by grouma** [comment]
We worked around this issue but I have a feeling this is an SDK issue. cc @bkonyi thoughts? Anna and I have been unsuccessful in creating a minimal repo but I can walk you through what it takes to reproduce.

**Comment by bkonyi** [comment]
`Directory.current` calls `getcwd()` on Linux by default and the only time that should result in `errno == 2` is when the CWD has been deleted. Is it possible that could be happening?

**Comment by grouma** [comment]
> Is it possible that could be happening?

We shouldn't be deleting the CWD. I don't think we change the CWD either. This could be a citc workspace so maybe it has something to do with that?

**Comment by annagrin** [comment]
> Directory.current calls getcwd() on Linux by default and the only time that should result in errno == 2 is when the CWD has been deleted. Is it possible that could be happening?

I run `strace` to collect all file-related system calls and did not see current directory changing to anything that is removed later. I can collect it again and share if needed.

**Comment by annagrin** [comment]
Labelling as p4 until it happens again.
