### ISSUE TITLE
The Flutter SDK is not available.

### ISSUE THREAD

**Issue by makhosravi** [dart-lang/webdev#1332]
Hi,
I have a problem which I hope you can help me with.
I'm using 
```
webdev v2.7.2 
build_runner: ^1.11.0
build_test: ^1.3.0
build_web_compilers: ^2.12.0
```
and while running ```webdev build --output web:build``` or just ```webdev build``` I encounter this error:
```
[INFO] Reading cached asset graph completed, took 426ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 259ms
[INFO] Caching finalized dependency graph completed, took 359ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 179ms
[INFO] Creating merged output dir `build` completed, took 595ms
[INFO] Writing asset manifest completed, took 2ms
[INFO] Succeeded after 1.4s with 0 outputs (0 actions)
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: D:\Android\FlutterSDK\flutter\bin\cache\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:66:5)
#1      PubspecLock.read (package:webdev/src/pubspec.dart:80:11)
#2      readPubspecLock (package:webdev/src/command/shared.dart:100:39)
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:53:29)
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:40:24)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:218:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:21:56)
#10     main (file:///C:/Users/asus/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/webdev-2.7.2/bin/webdev.dart:19:22)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

I don't know what could be the problem and why is my Flutter SDK not available.
Can you help me with this and guide me?

Thank you for your support.

**Comment by grouma** [comment]
Webdev is orthogonal to Flutter. It should be used for vanilla Dart web development. When you launch webdev it will validate your pubspec by starting the pub [process](https://github.com/dart-lang/webdev/blob/de05cf9fbbfe088be74bb61df4a138289a94d902/webdev/lib/src/pubspec.dart#L58). It looks like the one on your system path points to pub contained in a Flutter SDK folder.

Make sure the Dart SDK is installed correctly and that your environmental path correctly points to it.
