### ISSUE TITLE
flutter CI flakes: getStack: (-32603) getStack: NoSuchMethodError: The method 'toJson' was called on null.

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#1369]
We have seen flakes in flutter CI that seem due to dwds returning a null stack periodically.

```
00:41 +0 -1: test/web.shard/debugger_stepping_web_test.dart: Web debugger can step over statements [E]                                                                                                 
  getStack: (-32603) getStack: NoSuchMethodError: The method 'toJson' was called on null.
  Receiver: null
  Tried calling: toJson()
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
  #1      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1602:28)
  <asynchronous suspension>
  
  package:vm_service/src/vm_service.dart 1626:45        new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2109:21        VmService._call
  package:vm_service/src/vm_service.dart 1913:61        VmService.getStack
  test/integration.shard/test_driver.dart 334:42        FlutterTestDriver.getTopStackFrame
  ===== asynchronous gap ===========================
  test/integration.shard/test_driver.dart 343:25        FlutterTestDriver.getSourceLocation
  ===== asynchronous gap ===========================
  test/web.shard/debugger_stepping_web_test.dart 40:39  main.<fn>
```

Related: Flutter issue: flutter/flutter#84012
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2947/overview

another failure on flutter hhh https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840551373789240880/+/u/flutter_test_tool_tests/stdout

**Comment by annagrin** [comment]
Th fix is in the following PRs:
https://github.com/flutter/flutter/pull/87278
https://github.com/dart-lang/webdev/pull/1370
