### ISSUE TITLE
Evaluating a variable that is a package:http multipartFile twice results in an error

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#1519]
This was raised at https://github.com/Dart-Code/Dart-Code/issues/3836 but I think it's a dwds issue.

In a Flutter app, given this code:

```dart
final bytes = utf8.encode('test');
final multipartFile = http.MultipartFile(
    'picture', http.ByteStream.fromBytes(bytes), bytes.length,
    filename: 'danny.txt');
```

Pausing after the code in the debugger and hovering over `multipartFile` works fine the first time, but produces an error the second time. The VM Service traffic looks like this:

```
# FIRST HOVER

[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"27","jsonrpc":"2.0","method":"evaluateInFrame","params":{"disableBreakpoints":true,"expression":"multipartFile","frameIndex":0,"isolateId":"1"}}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"@Instance","id":"-4002533707801560989.1.143","kind":"PlainInstance","identityHashCode":311129437,"class":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}}},"id":"27"}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"28","jsonrpc":"2.0","method":"invoke","params":{"argumentIds":[],"disableBreakpoints":true,"isolateId":"1","selector":"toString","targetId":"-4002533707801560989.1.143"}}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"@Instance","id":"#StringInstanceRef#Instance of 'MultipartFile'","kind":"String","identityHashCode":115650977,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"Instance of 'MultipartFile'","length":27},"id":"28"}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"29","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"1","objectId":"-4002533707801560989.1.143"}}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"Instance","id":"-4002533707801560989.1.143","class":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"kind":"PlainInstance","identityHashCode":311129437,"fields":[{"decl":{"type":"@Field","id":"703","name":"_isFinalized","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"702","kind":"Type","identityHashCode":846105257,"class":{"type":"@Class","id":"classes|dart:core|Bool","name":"Bool","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}}},"const":false,"final":false,"static":false},"value":{"type":"@Instance","id":"objects/bool-false","kind":"Bool","identityHashCode":720935139,"class":{"type":"@Class","id":"classes|dart:core|Bool","name":"Bool","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"false"}},{"decl":{"type":"@Field","id":"715","name":"_stream","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"714","kind":"Type","identityHashCode":231618448,"class":{"type":"@Class","id":"classes|package:http/src/byte_stream.dart|ByteStream","name":"ByteStream","library":{"type":"@Library","id":"package:http/src/byte_stream.dart","name":"package:http/src/byte_stream.dart","uri":"package:http/src/byte_stream.dart"}}},"const":false,"final":false,"static":false},"value":{"type":"@Instance","id":"-4002533707801560989.1.148","kind":"PlainInstance","identityHashCode":936427497,"class":{"type":"@Class","id":"classes|package:http/src/byte_stream.dart|ByteStream","name":"ByteStream","library":{"type":"@Library","id":"package:http/src/byte_stream.dart","name":"package:http/src/byte_stream.dart","uri":"package:http/src/byte_stream.dart"}}}},{"decl":{"type":"@Field","id":"718","name":"contentType","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"717","kind":"Type","identityHashCode":71509113,"class":{"type":"@Class","id":"classes|package:http_parser/src/media_type.dart|MediaType","name":"MediaType","library":{"type":"@Library","id":"package:http_parser/src/media_type.dart","name":"package:http_parser/src/media_type.dart","uri":"package:http_parser/src/media_type.dart"}}},"const":false,"final":false,"static":false},"value":{"type":"@Instance","id":"-4002533707801560989.1.150","kind":"PlainInstance","identityHashCode":920239332,"class":{"type":"@Class","id":"classes|package:http_parser/src/media_type.dart|MediaType","name":"MediaType","library":{"type":"@Library","id":"package:http_parser/src/media_type.dart","name":"package:http_parser/src/media_type.dart","uri":"package:http_parser/src/media_type.dart"}}}},{"decl":{"type":"@Field","id":"706","name":"field","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"705","kind":"Type","identityHashCode":105853555,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}}},"const":false,"final":false,"static":false},"value":{"type":"@Instance","id":"#StringInstanceRef#picture","kind":"String","identityHashCode":166010549,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"picture","length":7}},{"decl":{"type":"@Field","id":"712","name":"filename","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"711","kind":"Type","identityHashCode":850461011,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}}},"const":false,"final":false,"static":false},"value":{"type":"@Instance","id":"#StringInstanceRef#danny.txt","kind":"String","identityHashCode":179443866,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"danny.txt","length":9}},{"decl":{"type":"@Field","id":"709","name":"length","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"708","kind":"Type","identityHashCode":347131691,"class":{"type":"@Class","id":"classes|dart:core|Double","name":"Double","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}}},"const":false,"final":false,"static":false},"value":{"type":"@Instance","id":"objects/int-4","kind":"Double","identityHashCode":1069851199,"class":{"type":"@Class","id":"classes|dart:core|Double","name":"Double","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"4"}}]},"id":"29"}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"30","jsonrpc":"2.0","method":"invoke","params":{"argumentIds":[],"disableBreakpoints":true,"isolateId":"1","selector":"toString","targetId":"-4002533707801560989.1.148"}}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"31","jsonrpc":"2.0","method":"invoke","params":{"argumentIds":[],"disableBreakpoints":true,"isolateId":"1","selector":"toString","targetId":"-4002533707801560989.1.150"}}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"32","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"1","objectId":"classes|package:http/src/multipart_file.dart|MultipartFile"}}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"@Instance","id":"#StringInstanceRef#Instance of 'ByteStream'","kind":"String","identityHashCode":756878539,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"Instance of 'ByteStream'","length":24},"id":"30"}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"@Instance","id":"#StringInstanceRef#application/octet-stream","kind":"String","identityHashCode":1016908090,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"application/octet-stream","length":24},"id":"31"}
[6:10:17 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"},"abstract":false,"const":false,"traceAllocations":false,"interfaces":[],"fields":[{"type":"@Field","id":"721","name":"field","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"720","kind":"Type","identityHashCode":827752095,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}}},"const":false,"final":true,"static":false},{"type":"@Field","id":"724","name":"length","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"723","kind":"Type","identityHashCode":63156252,"class":{"type":"@Class","id":"classes|dart:core|int","name":"int","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}}},"const":false,"final":true,"static":false},{"type":"@Field","id":"727","name":"filename","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"726","kind":"Type","identityHashCode":982293934,"class":{"type":"@Class","id":"classes|null|String?","name":"String?","library":{"type":"@Library","id":null,"name":null,"uri":null}}},"const":false,"final":true,"static":false},{"type":"@Field","id":"730","name":"contentType","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"declaredType":{"type":"@Instance","id":"729","kind":"Type","identityHashCode":197902376,"class":{"type":"@Class","id":"classes|package:http_parser/src/media_type.dart|MediaType","name":"MediaType","library":{"type":"@Library","id":"package:http_parser/src/media_type.dart","name":"package:http_parser/src/media_type.dart","uri":"package:http_parser/src/media_type.dart"}}},"const":false,"final":true,"static":false}],"functions":[{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|field","name":"field","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|length","name":"length","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|filename","name":"filename","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|contentType","name":"contentType","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|isFinalized","name":"isFinalized","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|finalize","name":"finalize","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|_equals","name":"_equals","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|hashCode","name":"hashCode","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|toString","name":"toString","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|noSuchMethod","name":"noSuchMethod","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|runtimeType","name":"runtimeType","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":false,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|fromBytes","name":"fromBytes","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":true,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|fromString","name":"fromString","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":true,"const":false,"implicit":false},{"type":"@Function","id":"methods|classes|package:http/src/multipart_file.dart|MultipartFile|fromPath","name":"fromPath","owner":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}},"static":true,"const":false,"implicit":false}],"subclasses":[]},"id":"32"}


# SECOND HOVER

[6:10:22 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"33","jsonrpc":"2.0","method":"evaluateInFrame","params":{"disableBreakpoints":true,"expression":"multipartFile","frameIndex":0,"isolateId":"1"}}
[6:10:22 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"@Instance","id":"-4002533707801560989.1.155","kind":"PlainInstance","identityHashCode":736175874,"class":{"type":"@Class","id":"classes|package:http/src/multipart_file.dart|MultipartFile","name":"MultipartFile","library":{"type":"@Library","id":"package:http/src/multipart_file.dart","name":"package:http/src/multipart_file.dart","uri":"package:http/src/multipart_file.dart"}}},"id":"33"}
[6:10:22 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"34","jsonrpc":"2.0","method":"invoke","params":{"argumentIds":[],"disableBreakpoints":true,"isolateId":"1","selector":"toString","targetId":"-4002533707801560989.1.155"}}
[6:10:22 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","result":{"type":"@Instance","id":"#StringInstanceRef#Instance of 'MultipartFile'","kind":"String","identityHashCode":115650977,"class":{"type":"@Class","id":"classes|dart:core|String","name":"String","library":{"type":"@Library","id":"dart:core","name":"dart:core","uri":"dart:core"}},"valueAsString":"Instance of 'MultipartFile'","length":27},"id":"34"}
[6:10:22 PM] [VmService] [Info] [Flutter (Chrome)] ==> {"id":"35","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"1","objectId":"-4002533707801560989.1.155"}}
# the problematic response 👇
[6:10:22 PM] [VmService] [Info] [Flutter (Chrome)] <== {"jsonrpc":"2.0","error":{"code":-32603,"message":"getObject: NoSuchMethodError: The getter 'classRef' was called on null.\nReceiver: null\nTried calling: classRef","data":{"details":"#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)\n#1      InstanceHelper._fieldFor (package:dwds/src/debugging/instance.dart:155:34)\n<asynchronous suspension>\n#2      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)\n<asynchronous suspension>\n","request":{"id":"35","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"1","objectId":"-4002533707801560989.1.155"}}}},"id":"35"}
```

**Comment by bkonyi** [comment]
@DanTup is this still an issue by any chance?

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this any more.
