### ISSUE TITLE
DartDevcFrontendServerClient throws null safety exception

### ISSUE THREAD

**Issue by Ehesp** [dart-lang/webdev#1546]
When running the `DartDevcFrontendServerClient` compiler, an exception will be thrown:

```
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:472:9)
#1      JavaScriptBundler.compile (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/src/javascript_bundle.dart:152:33)
#2      FrontendCompiler.writeJavascriptBundle (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:693:47)
```

This can be reproduced by running the example within the `frontend_server_client` package:

```
cd frontend_server_client
dart example/web_client.dart
```

**Comment by annagrin** [comment]
@jakemac53 FYI

**Comment by jakemac53** [comment]
Looks like the issue here is we need to use the sound platform dill file, as well as a sound dart_sdk.js file, but the latter we will have to compile ourselves.
