### ISSUE TITLE
ChromeProxyService does not implement setIsolatePauseMode

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#1627]
I'm preparing to switch VS Code users over from the debug adapter shipped in Dart-Code to the ones that are now shipping in the Dart+Flutter SDKs. However I found that trying to run Flutter apps on the Chrome device fails with this error:

```
Oops; flutter has exited unexpectedly: "setIsolatePauseMode: (-32603) setIsolatePauseMode: NoSuchMethodError: Class 'ChromeProxyService' has no instance method 'setIsolatePauseMode' with matching arguments.
Receiver: Instance of 'ChromeProxyService'
Tried calling: setIsolatePauseMode("1", exceptionPauseMode: "Unhandled", shouldPauseOnExit: null)
Found: setIsolatePauseMode(String, {String exceptionPauseMode, bool shouldPauseOnExit}) => Future<Success>
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      ChromeProxyService.noSuchMethod (package:dwds/src/services/chrome_proxy_service.dart:1079:18)
#2      ChromeProxyService.setIsolatePauseMode (package:dwds/src/services/chrome_proxy_service.dart:43:7)
```

I believe the issue is that in https://github.com/dart-lang/sdk/commit/0cad0e722483310a995732b44cc83c5689f9f7c9 the debug adapter was switched from `setExceptionPauseMode` to `setIsolatePauseMode` and that's not implemented by the proxy.

@bkonyi slightly related - should `package:vm_service` handle falling back to the old method if the VM Service it's connected to doesn't support it? If not, should the DAP code be switched back to the old method until this is implemented?

**Comment by DanTup** [comment]
As far as I know, this was completed a while back. Feel free to re-open if there's anything outstanding.
