### ISSUE TITLE
webdev serve --auto restart fails with "Uncaught TypeError: J.get$first$ax(...).main is not a function"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/webdev#1728]
```
Uncaught TypeError: J.get$first$ax(...).main is not a function
    at RequireRestarter__reload_closure.call$0 (client.js:25048:60)
    at Object.Primitives_applyFunction (client.js:941:30)
    at Object.Function_apply (client.js:4922:16)
    at _callDartFunctionFast (client.js:7485:16)
    at client.js:7476:18
    at <anonymous>:1:8
    at Object.runMain (client.js:8817:21)
    at client.js:24806:17
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3475:15)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11585:12)
    at _awaitOnObject_closure.call$1 (client.js:11573:32)
    at StaticClosure._rootRunUnary (client.js:3837:18)
    at _CustomZone.runUnary$2$2 (client.js:12991:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (client.js:12017:51)
    at Object._Future__propagateToListeners (client.js:3617:93)
    at _Future._completeWithValue$1 (client.js:11843:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (client.js:11945:18)
    at StaticClosure._rootRun (client.js:3822:16)
    at _CustomZone.run$1$1 (client.js:12983:39)
    at _CustomZone.runGuarded$1 (client.js:12926:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (client.js:13121:25)
    at Object._microtaskLoop (client.js:3681:24)
    at StaticClosure._startMicrotaskLoop (client.js:3687:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:11461:9)
    at invokeClosure (client.js:1274:26)
    at MutationObserver.<anonymous> (client.js:1293:18)
```

I can't tell why, or I'd provide more information. My `main` is fairly simple:

![](https://user-images.githubusercontent.com/168174/185980628-f9a6c847-7606-41d4-ae18-f80af2089d0d.png)

`webdev --version` is `2.7.10` ...
running on `dart --version` `Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "macos_arm64"`.

**Comment by bkonyi** [comment]
We should verify whether or not this is still happening.
