### ISSUE TITLE
Unhandled error detected in the injected client.js script.

### ISSUE THREAD

**Issue by cecastosic** [dart-lang/webdev#1896]
Bad state: Cannot add event after closing
Bad state: Cannot add event after closing
    at Object.wrapException (http://localhost:40331/dwds/src/injected/client.js:1075:17)
    at _AsyncStreamController.add$1 (http://localhost:40331/dwds/src/injected/client.js:12177:17)
    at _StreamSinkWrapper.add$1 (http://localhost:40331/dwds/src/injected/client.js:12357:27)
    at main__closure0.call$1 (http://localhost:40331/dwds/src/injected/client.js:24313:10)
    at StaticClosure._rootRunUnary (http://localhost:40331/dwds/src/injected/client.js:3837:18)
    at _CustomZone.runUnary$2$2 (http://localhost:40331/dwds/src/injected/client.js:12970:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:40331/dwds/src/injected/client.js:12917:14)
    at _ControllerSubscription._sendData$1 (http://localhost:40331/dwds/src/injected/client.js:12504:19)
    at _DelayedData.perform$1 (http://localhost:40331/dwds/src/injected/client.js:12686:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:40331/dwds/src/injected/client.js:12735:14)
    at StaticClosure._rootRun (http://localhost:40331/dwds/src/injected/client.js:3816:18)
    at _CustomZone.run$1$1 (http://localhost:40331/dwds/src/injected/client.js:12962:39)
    at _CustomZone.runGuarded$1 (http://localhost:40331/dwds/src/injected/client.js:12905:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:40331/dwds/src/injected/client.js:13100:25)
    at StaticClosure._rootRun (http://localhost:40331/dwds/src/injected/client.js:3822:16)
    at _CustomZone.run$1$1 (http://localhost:40331/dwds/src/injected/client.js:12962:39)
    at _CustomZone.runGuarded$1 (http://localhost:40331/dwds/src/injected/client.js:12905:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:40331/dwds/src/injected/client.js:13100:25)
    at Object._microtaskLoop (http://localhost:40331/dwds/src/injected/client.js:3681:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:40331/dwds/src/injected/client.js:3687:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:40331/dwds/src/injected/client.js:11440:9)
    at invokeClosure (http://localhost:40331/dwds/src/injected/client.js:1274:26)
    at MutationObserver.<anonymous> (http://localhost:40331/dwds/src/injected/client.js:1293:18)

![Screenshot 2023-01-18 at 15 05 38](https://user-images.githubusercontent.com/10253713/213192061-9d324902-9449-4bb8-ab4a-9c6ef56cbfc2.png)

When running the integration tests as part of the GitHub actions

**Comment by elliette** [comment]
Hi @cecastosic - do you need to connect a debugger as part of your integration tests? If not, the suggestion of passing the `--no-injected-client` flag should work to disable this.

**Comment by cecastosic** [comment]
I am using the flutter driver to run tests. Where should I pass the `--no-injected-client` flag?

**Comment by bkonyi** [comment]
@cecastosic is still still a problem you're seeing?

**Comment by bkonyi** [comment]
Closing due to inactivity.
