### ISSUE TITLE
Can't access debug web app on localhost but works on 127.0.0.1

### ISSUE THREAD

**Issue by dumbPy** [dart-lang/webdev#1988]
## Steps to reproduce:
```
# create a web project
dart create -t web myapp
cd myapp
dart pub global activate webdev
```
start debug daemon (since that's what vscode seems to be doing)
```
webdev daemon web:8080
```

This starts the web app at `127.0.0.1:8080`

If I change the browser address to `localhost:8080` it crashes the daemon with below error
```
Unhandled exception:
WebSocketException: Connection to 'http://127.0.0.1:62716/v5_zz3h5jg0=/ws#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80:28)
#3      connect (package:web_socket_channel/src/_connect_io.dart:15:24)
#4      new WebSocketChannel.connect (package:web_socket_channel/src/channel.dart:115:16)
#5      _defaultWebSocketBuilder (package:dds/src/dds_impl.dart:51:27)
#6      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:78:40)
#7      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:19)
<asynchronous suspension>
#8      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:154:12)
<asynchronous suspension>
#9      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:466:7)
<asynchronous suspension>
#10     DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:241:21)
<asynchronous suspension>
#11     Dwds.debugConnection (package:dwds/dart_web_debug_service.dart:61:30)
<asynchronous suspension>
#12     AppDomain._handleAppConnections (package:webdev/src/daemon/app_domain.dart:62:29)
<asynchronous suspension>
```

**Comment by annagrin** [comment]
This looks like a DDS issue.

@bkonyi FYI
@dumbPy for a workaround, you can try running `webdev daemon web:8080 --disable-dds`

I will transfer this issue to the dart SDK repo.
