### ISSUE TITLE
debugging localhost iframe flutter window from another web server

### ISSUE THREAD

**Issue by YulianAm** [dart-lang/webdev#2173]
SecurityError: Blocked a frame with origin "http://localhost:56004" from accessing a cross-origin frame.
Error: Blocked a frame with origin "http://localhost:56004" from accessing a cross-origin frame.
    at Object._launchCommunicationWithDebugExtension (http://localhost:56004/dwds/src/injected/client.js:8768:23)
    at http://localhost:56004/dwds/src/injected/client.js:24644:17
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56004/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56004/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56004/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:56004/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56004/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56004/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:56004/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:56004/dwds/src/injected/client.js:11933:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:56004/dwds/src/injected/client.js:11649:14)
    at Object._asyncReturn (http://localhost:56004/dwds/src/injected/client.js:3547:17)
    at http://localhost:56004/dwds/src/injected/client.js:8919:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56004/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56004/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56004/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:56004/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56004/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56004/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:56004/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:56004/dwds/src/injected/client.js:11933:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:56004/dwds/src/injected/client.js:11649:14)
    at Object._asyncReturn (http://localhost:56004/dwds/src/injected/client.js:3547:17)
    at http://localhost:56004/dwds/src/injected/client.js:25215:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56004/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56004/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56004/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:56004/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56004/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56004/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:56004/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:56004/dwds/src/injected/client.js:11933:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:56004/dwds/src/injected/client.js:11649:14)
    at Object._asyncReturn (http://localhost:56004/dwds/src/injected/client.js:3547:17)
    at http://localhost:56004/dwds/src/injected/client.js:25192:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56004/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56004/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56004/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:56004/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56004/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56004/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:56004/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:56004/dwds/src/injected/client.js:11933:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:56004/dwds/src/injected/client.js:12036:18)
    at StaticClosure._rootRun (http://localhost:56004/dwds/src/injected/client.js:3924:16)
    at _CustomZone.run$1$1 (http://localhost:56004/dwds/src/injected/client.js:13066:39)
    at _CustomZone.runGuarded$1 (http://localhost:56004/dwds/src/injected/client.js:13009:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:56004/dwds/src/injected/client.js:13204:25)
    at Object._microtaskLoop (http://localhost:56004/dwds/src/injected/client.js:3783:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:56004/dwds/src/injected/client.js:3789:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:56004/dwds/src/injected/client.js:11552:9)
    at invokeClosure (http://localhost:56004/dwds/src/injected/client.js:1229:26)
    at MutationObserver.<anonymous> (http://localhost:56004/dwds/src/injected/client.js:1248:18)

**Comment by YulianAm** [comment]
CORS error
