### ISSUE TITLE
Debugging features are broken after a reload due to missing execution context

### ISSUE THREAD

**Issue by annagrin** [dart-lang/webdev#2284]
I can only see this internally, after putting a breakpoint in main.dart and reloading the page (could be a new chrome version?)

```
11:17:32.500 INFO: MetadataProvider: Loading debug metadata...
11:17:32.504 WARNING: RemoteDebuggerExecutionContext: Timed out finding an execution context after 100 ms.
11:17:32.504 SEVERE: AppInspector: Missing execution context ID: Bad state: No context with the running Dart application.
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:65:7)
<asynchronous suspension>
#1      AppInspector.contextId (package:dwds/src/debugging/inspector.dart:186:14)
<asynchronous suspension>
#2      AppInspector._jsCallFunction (package:dwds/src/debugging/inspector.dart:268:31)
<asynchronous suspension>
#3      AppInspector.mapExceptionStackTrace (package:dwds/src/debugging/inspector.dart:778:22)
<asynchronous suspension>
#4      ChromeProxyService._chromeConsoleStreamController.<anonymous closure>.<anonymous closure> (package:dwds/src/services/chrome_proxy_service.dart:1279:29)
<asynchronous suspension>


11:17:32.576 INFO: MetadataProvider: Loaded debug metadata (sound null safety)
11:17:32.576 INFO: ChromeProxyService: Initializing expression compiler for ads/acx2/demo/web/demo_ddc_bundle.app.bootstrap.js with sound null safety: true
11:17:32.652 INFO: ExpressionCompilerService: Updating dependencies...
11:17:32.973 WARNING: RemoteDebuggerExecutionContext: Timed out finding an execution context after 100 ms.
11:17:32.973 SEVERE: AppInspector: Missing execution context ID: Bad state: No context with the running Dart application.
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:65:7)
<asynchronous suspension>
#1      AppInspector.contextId (package:dwds/src/debugging/inspector.dart:186:14)
<asynchronous suspension>
#2      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:755:20)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:121:35)
<asynchronous suspension>
#4      AppInspector.create (package:dwds/src/debugging/inspector.dart:178:5)
<asynchronous suspension>
#5      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:258:18)
<asynchronous suspension>
#6      DevHandler._handleConnectRequest (package:dwds/src/handlers/dev_handler.dart:460:7)
<asynchronous suspension>
#7      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:268:15)
```

**Comment by annagrin** [comment]
I investigated this a bit - the cause is an exception that an unrelated chrome extension is throwing before the injected client is loaded. We try the map the exception to dart and fail getting dart execution context id, which can be only correctly detected after the client is loaded. 

We might need to remember the old contexts and periodically try to detect a dart context in them again if the original context detection times out.
