### ISSUE TITLE
Debug launch error for web (chrome) - Assertion failed: "boolean expression must not be null"

### ISSUE THREAD

**Issue by solbirn** [dart-lang/webdev#2331]
Flutter 3.16.1
Web 0.3.0
OS: MacOS 14

Error:
```
Assertion failed: "boolean expression must not be null"
Assertion failed: "boolean expression must not be null"
    at Object.wrapException (http://localhost:5066/dwds/src/injected/client.js:1420:43)
    at Object.assertThrow (http://localhost:5066/dwds/src/injected/client.js:1871:15)
    at Object.boolConversionCheck (http://localhost:5066/dwds/src/injected/client.js:1867:11)
    at http://localhost:5066/dwds/src/injected/client.js:25481:21
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5066/dwds/src/injected/client.js:4009:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5066/dwds/src/injected/client.js:12242:12)
    at _awaitOnObject_closure.call$1 (http://localhost:5066/dwds/src/injected/client.js:12230:32)
    at StaticClosure._rootRunUnary (http://localhost:5066/dwds/src/injected/client.js:4391:18)
    at _CustomZone.runUnary$2$2 (http://localhost:5066/dwds/src/injected/client.js:13637:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:5066/dwds/src/injected/client.js:12668:51)
    at Object._Future__propagateToListeners (http://localhost:5066/dwds/src/injected/client.js:4174:93)
    at _Future._completeWithValue$1 (http://localhost:5066/dwds/src/injected/client.js:12504:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:5066/dwds/src/injected/client.js:12216:14)
    at Object._asyncReturn (http://localhost:5066/dwds/src/injected/client.js:3981:17)
    at http://localhost:5066/dwds/src/injected/client.js:9758:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5066/dwds/src/injected/client.js:4009:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5066/dwds/src/injected/client.js:12242:12)
    at _awaitOnObject_closure.call$1 (http://localhost:5066/dwds/src/injected/client.js:12230:32)
    at StaticClosure._rootRunUnary (http://localhost:5066/dwds/src/injected/client.js:4391:18)
    at _CustomZone.runUnary$2$2 (http://localhost:5066/dwds/src/injected/client.js:13637:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:5066/dwds/src/injected/client.js:12668:51)
    at Object._Future__propagateToListeners (http://localhost:5066/dwds/src/injected/client.js:4174:93)
    at _Future._completeWithValue$1 (http://localhost:5066/dwds/src/injected/client.js:12504:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:5066/dwds/src/injected/client.js:12216:14)
    at Object._asyncReturn (http://localhost:5066/dwds/src/injected/client.js:3981:17)
    at http://localhost:5066/dwds/src/injected/client.js:26112:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5066/dwds/src/injected/client.js:4009:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5066/dwds/src/injected/client.js:12242:12)
    at _awaitOnObject_closure.call$1 (http://localhost:5066/dwds/src/injected/client.js:12230:32)
    at StaticClosure._rootRunUnary (http://localhost:5066/dwds/src/injected/client.js:4391:18)
    at _CustomZone.runUnary$2$2 (http://localhost:5066/dwds/src/injected/client.js:13637:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:5066/dwds/src/injected/client.js:12668:51)
    at Object._Future__propagateToListeners (http://localhost:5066/dwds/src/injected/client.js:4174:93)
    at _Future._completeWithValue$1 (http://localhost:5066/dwds/src/injected/client.js:12504:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:5066/dwds/src/injected/client.js:12216:14)
    at Object._asyncReturn (http://localhost:5066/dwds/src/injected/client.js:3981:17)
    at http://localhost:5066/dwds/src/injected/client.js:26089:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5066/dwds/src/injected/client.js:4009:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5066/dwds/src/injected/client.js:12242:12)
    at _awaitOnObject_closure.call$1 (http://localhost:5066/dwds/src/injected/client.js:12230:32)
    at StaticClosure._rootRunUnary (http://localhost:5066/dwds/src/injected/client.js:4391:18)
    at _CustomZone.runUnary$2$2 (http://localhost:5066/dwds/src/injected/client.js:13637:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:5066/dwds/src/injected/client.js:12668:51)
    at Object._Future__propagateToListeners (http://localhost:5066/dwds/src/injected/client.js:4174:93)
    at _Future._completeWithValue$1 (http://localhost:5066/dwds/src/injected/client.js:12504:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:5066/dwds/src/injected/client.js:12608:18)
    at StaticClosure._rootRun (http://localhost:5066/dwds/src/injected/client.js:4376:16)
    at _CustomZone.run$1$1 (http://localhost:5066/dwds/src/injected/client.js:13629:39)
    at _CustomZone.runGuarded$1 (http://localhost:5066/dwds/src/injected/client.js:13572:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:5066/dwds/src/injected/client.js:13767:25)
    at Object._microtaskLoop (http://localhost:5066/dwds/src/injected/client.js:4235:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:5066/dwds/src/injected/client.js:4241:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:5066/dwds/src/injected/client.js:12119:9)
```

client.js code
```
if (A.boolConversionCheck(self.$dwdsEnableDevToolsLaunch)) {
                t1 = window;
                t1.toString;
                A._EventStreamSubscription$(t1, "keydown", type$.nullable_void_Function_KeyboardEvent._as(new A.main__closure6()), false, type$.KeyboardEvent);
              }
```

**Comment by solbirn** [comment]
Closing. Updated SDK to 3.16.5 and issue has resolved.
