### ISSUE TITLE
after upgrading to flutter 3.19.3 , I am getting  the error below   when I  try to build and run on web.

### ISSUE THREAD

**Issue by kimemia21** [dart-lang/webdev#2391]
Assertion failed: "boolean expression must not be null"
Assertion failed: "boolean expression must not be null"
    at Object.wrapException (http://localhost:56086/dwds/src/injected/client.js:1036:17)
    at Object.assertThrow (http://localhost:56086/dwds/src/injected/client.js:1482:15)
    at Object.boolConversionCheck (http://localhost:56086/dwds/src/injected/client.js:1478:11)
    at http://localhost:56086/dwds/src/injected/client.js:24791:21
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56086/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56086/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56086/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:56086/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56086/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56086/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:56086/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:56086/dwds/src/injected/client.js:11956:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:56086/dwds/src/injected/client.js:11672:14)
    at Object._asyncReturn (http://localhost:56086/dwds/src/injected/client.js:3561:17)
    at http://localhost:56086/dwds/src/injected/client.js:8926:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56086/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56086/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56086/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:56086/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56086/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56086/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:56086/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:56086/dwds/src/injected/client.js:11956:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:56086/dwds/src/injected/client.js:11672:14)
    at Object._asyncReturn (http://localhost:56086/dwds/src/injected/client.js:3561:17)
    at http://localhost:56086/dwds/src/injected/client.js:25367:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56086/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56086/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56086/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:56086/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56086/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56086/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:56086/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:56086/dwds/src/injected/client.js:11956:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:56086/dwds/src/injected/client.js:11672:14)
    at Object._asyncReturn (http://localhost:56086/dwds/src/injected/client.js:3561:17)
    at http://localhost:56086/dwds/src/injected/client.js:25344:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56086/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56086/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:56086/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:56086/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:56086/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:56086/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:56086/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:56086/dwds/src/injected/client.js:11956:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:56086/dwds/src/injected/client.js:12059:18)
    at StaticClosure._rootRun (http://localhost:56086/dwds/src/injected/client.js:3933:16)
    at _CustomZone.run$1$1 (http://localhost:56086/dwds/src/injected/client.js:13087:39)
    at _CustomZone.runGuarded$1 (http://localhost:56086/dwds/src/injected/client.js:13030:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:56086/dwds/src/injected/client.js:13225:25)
    at Object._microtaskLoop (http://localhost:56086/dwds/src/injected/client.js:3792:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:56086/dwds/src/injected/client.js:3798:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:56086/dwds/src/injected/client.js:11575:9)
    at invokeClosure (http://localhost:56086/dwds/src/injected/client.js:1238:26)
    at MutationObserver.<anonymous> (http://localhost:56086/dwds/src/injected/client.js:1257:18)

**Comment by elliette** [comment]
Interesting, this looks the same as https://github.com/dart-lang/webdev/issues/2332 which was resolved by updating to the latest Flutter stable (which you are already on).

Could you try the steps suggested here: https://github.com/dart-lang/webdev/issues/2332#issuecomment-1885432333

Thanks!
