### ISSUE TITLE
 Assertion failed: "boolean expression must not be null"

### ISSUE THREAD

**Issue by pavanjoshi914** [dart-lang/webdev#2454]
```Assertion failed: "boolean expression must not be null"

    at Object.wrapException (http://localhost:52700/dwds/src/injected/client.js:1027:17)
    at Object.assertThrow (http://localhost:52700/dwds/src/injected/client.js:1473:15)
    at Object.boolConversionCheck (http://localhost:52700/dwds/src/injected/client.js:1469:11)
    at http://localhost:52700/dwds/src/injected/client.js:24630:21
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:52700/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:52700/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:52700/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:52700/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:52700/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:52700/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:52700/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:52700/dwds/src/injected/client.js:11933:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:52700/dwds/src/injected/client.js:11649:14)
    at Object._asyncReturn (http://localhost:52700/dwds/src/injected/client.js:3547:17)
    at http://localhost:52700/dwds/src/injected/client.js:8919:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:52700/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:52700/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:52700/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:52700/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:52700/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:52700/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:52700/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:52700/dwds/src/injected/client.js:11933:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:52700/dwds/src/injected/client.js:11649:14)
    at Object._asyncReturn (http://localhost:52700/dwds/src/injected/client.js:3547:17)
    at http://localhost:52700/dwds/src/injected/client.js:25215:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:52700/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:52700/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:52700/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:52700/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:52700/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:52700/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:52700/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:52700/dwds/src/injected/client.js:11933:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:52700/dwds/src/injected/client.js:11649:14)
    at Object._asyncReturn (http://localhost:52700/dwds/src/injected/client.js:3547:17)
    at http://localhost:52700/dwds/src/injected/client.js:25192:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:52700/dwds/src/injected/client.js:3575:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:52700/dwds/src/injected/client.js:11675:12)
    at _awaitOnObject_closure.call$1 (http://localhost:52700/dwds/src/injected/client.js:11663:32)
    at StaticClosure._rootRunUnary (http://localhost:52700/dwds/src/injected/client.js:3939:18)
    at _CustomZone.runUnary$2$2 (http://localhost:52700/dwds/src/injected/client.js:13074:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:52700/dwds/src/injected/client.js:12102:51)
    at Object._Future__propagateToListeners (http://localhost:52700/dwds/src/injected/client.js:3722:93)
    at _Future._completeWithValue$1 (http://localhost:52700/dwds/src/injected/client.js:11933:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:52700/dwds/src/injected/client.js:12036:18)
    at StaticClosure._rootRun (http://localhost:52700/dwds/src/injected/client.js:3924:16)
    at _CustomZone.run$1$1 (http://localhost:52700/dwds/src/injected/client.js:13066:39)
    at _CustomZone.runGuarded$1 (http://localhost:52700/dwds/src/injected/client.js:13009:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:52700/dwds/src/injected/client.js:13204:25)
    at Object._microtaskLoop (http://localhost:52700/dwds/src/injected/client.js:3783:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:52700/dwds/src/injected/client.js:3789:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:52700/dwds/src/injected/client.js:11552:9)
    at invokeClosure (http://localhost:52700/dwds/src/injected/client.js:1229:26)
    at MutationObserver.<anonymous> (http://localhost:52700/dwds/src/injected/client.js:1248:18)
```

```
Flutter is already up to date on channel stable
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (3 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

**Comment by bkonyi** [comment]
Hi @pavanjoshi914, can you try the steps listed [here](https://github.com/dart-lang/webdev/issues/2332#issuecomment-1900495539) and see if that resolves your issue?

**Comment by pavanjoshi914** [comment]
it didn't worked facing same error

**Comment by bkonyi** [comment]
Can you also try the steps listed [here](https://github.com/dart-lang/webdev/issues/2332#issuecomment-1885432333)?

**Comment by bkonyi** [comment]
Closing due to inactivity.
