### ISSUE TITLE
`chrome_proxy_service_test.dart` failing with `TypeError: _ti[_eval] is not a function`

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/webdev#2473]
Multiple tests in `test/chrome_proxy_service_test.dart` started failing in the daily testing run with errors similar to the following:

```
❌ test/chrome_proxy_service_test.dart: shared context getObject Maps (failed)
  Retry: shared context getObject Maps
  Retry: shared context getObject Maps
  Retry: shared context getObject Maps
  Unexpected error from chrome devtools:
  text: Uncaught
  exception:
    preview: null
    description: TypeError: _ti[_eval] is not a function
      at Iterable.generate (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:19611:24)
      at Object._checkAndCall (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4562:16)
      at Object.callMethod (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4647:17)
      at Object.dsend (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4650:17)
      at <anonymous>:3:39
      at <anonymous>:10:9
    type: object
    value: null
  attempted JS eval: `          (function () {
              const sdk = require("dart_sdk");
              const iterable = sdk.dart.dsend(sdk.core.Iterable, "generate", [1001]);
              const list1 = sdk.dart.dsend(iterable, "toList", []);
              const reversed = sdk.dart.dload(list1, "reversed");
              const list2 = sdk.dart.dsend(reversed, "toList", []);
              const map = sdk.dart.dsend(list2, "asMap", []);
              const linkedMap = sdk.dart.dsend(sdk.collection.LinkedHashMap, "from", [map]);
              return linkedMap;
        })()`
  stack trace:
  generate()      http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 19610:23
  _checkAndCall() http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4561:15
  callMethod()    http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4646:16
  dsend()         http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4649:16
  ()               2:38
  ()               9:8
  
  package:dwds/src/utilities/server.dart 80:5       handleErrorIfPresent
  package:dwds/src/utilities/server.dart 94:3       getResultOrHandleError
  package:dwds/src/debugging/inspector.dart 335:20  AppInspector.jsEvaluate
  ===== asynchronous gap ===========================
  test/chrome_proxy_service_test.dart 716:21        main.<fn>.<fn>.<fn>
  Unexpected error from chrome devtools:
  text: Uncaught
  exception:
    preview: null
    description: TypeError: _ti[_eval] is not a function
      at Iterable.generate (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:19611:24)
      at Object._checkAndCall (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4562:16)
      at Object.callMethod (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4647:17)
      at Object.dsend (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4650:17)
      at <anonymous>:3:39
      at <anonymous>:10:9
    type: object
    value: null
  attempted JS eval: `          (function () {
              const sdk = require("dart_sdk");
              const iterable = sdk.dart.dsend(sdk.core.Iterable, "generate", [1001]);
              const list1 = sdk.dart.dsend(iterable, "toList", []);
              const reversed = sdk.dart.dload(list1, "reversed");
              const list2 = sdk.dart.dsend(reversed, "toList", []);
              const map = sdk.dart.dsend(list2, "asMap", []);
              const linkedMap = sdk.dart.dsend(sdk.collection.LinkedHashMap, "from", [map]);
              return linkedMap;
        })()`
  stack trace:
  generate()      http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 19610:23
  _checkAndCall() http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4561:15
  callMethod()    http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4646:16
  dsend()         http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4649:16
  ()               2:38
  ()               9:8
  
  package:dwds/src/utilities/server.dart 80:5       handleErrorIfPresent
  package:dwds/src/utilities/server.dart 94:3       getResultOrHandleError
  package:dwds/src/debugging/inspector.dart 335:20  AppInspector.jsEvaluate
  ===== asynchronous gap ===========================
  test/chrome_proxy_service_test.dart 716:21        main.<fn>.<fn>.<fn>
  Unexpected error from chrome devtools:
  text: Uncaught
  exception:
    preview: null
    description: TypeError: _ti[_eval] is not a function
      at Iterable.generate (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:19611:24)
      at Object._checkAndCall (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4562:16)
      at Object.callMethod (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4647:17)
      at Object.dsend (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4650:17)
      at <anonymous>:3:39
      at <anonymous>:10:9
    type: object
    value: null
  attempted JS eval: `          (function () {
              const sdk = require("dart_sdk");
              const iterable = sdk.dart.dsend(sdk.core.Iterable, "generate", [1001]);
              const list1 = sdk.dart.dsend(iterable, "toList", []);
              const reversed = sdk.dart.dload(list1, "reversed");
              const list2 = sdk.dart.dsend(reversed, "toList", []);
              const map = sdk.dart.dsend(list2, "asMap", []);
              const linkedMap = sdk.dart.dsend(sdk.collection.LinkedHashMap, "from", [map]);
              return linkedMap;
        })()`
  stack trace:
  generate()      http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 19610:23
  _checkAndCall() http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4561:15
  callMethod()    http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4646:16
  dsend()         http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4649:16
  ()               2:38
  ()               9:8
  
  package:dwds/src/utilities/server.dart 80:5       handleErrorIfPresent
  package:dwds/src/utilities/server.dart 94:3       getResultOrHandleError
  package:dwds/src/debugging/inspector.dart 335:20  AppInspector.jsEvaluate
  ===== asynchronous gap ===========================
  test/chrome_proxy_service_test.dart 716:21        main.<fn>.<fn>.<fn>
  Unexpected error from chrome devtools:
  text: Uncaught
  exception:
    preview: null
    description: TypeError: _ti[_eval] is not a function
      at Iterable.generate (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:19611:24)
      at Object._checkAndCall (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4562:16)
      at Object.callMethod (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4647:17)
      at Object.dsend (http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4650:17)
      at <anonymous>:3:39
      at <anonymous>:10:9
    type: object
    value: null
  attempted JS eval: `          (function () {
              const sdk = require("dart_sdk");
              const iterable = sdk.dart.dsend(sdk.core.Iterable, "generate", [1001]);
              const list1 = sdk.dart.dsend(iterable, "toList", []);
              const reversed = sdk.dart.dload(list1, "reversed");
              const list2 = sdk.dart.dsend(reversed, "toList", []);
              const map = sdk.dart.dsend(list2, "asMap", []);
              const linkedMap = sdk.dart.dsend(sdk.collection.LinkedHashMap, "from", [map]);
              return linkedMap;
        })()`
  stack trace:
  generate()      http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 19610:23
  _checkAndCall() http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4561:15
  callMethod()    http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4646:16
  dsend()         http://localhost:32883/packages/build_web_compilers/src/dev_compiler/dart_sdk.js 4649:16
  ()               2:38
  ()               9:8
  
  package:dwds/src/utilities/server.dart 80:5       handleErrorIfPresent
  package:dwds/src/utilities/server.dart 94:3       getResultOrHandleError
  package:dwds/src/debugging/inspector.dart 335:20  AppInspector.jsEvaluate
  ===== asynchronous gap ===========================
```

Full logs [here](https://github.com/dart-lang/webdev/actions/runs/10285790803/job/28464927549).

cc @biggs0125 @nshahan

**Comment by jyameo** [comment]
Closing this issue as the test above is no longer failing.
