### ISSUE TITLE
execution error of flutter web on chrome

### ISSUE THREAD

**Issue by mypro44489** [dart-lang/webdev#2532]
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

Assertion failed: "boolean expression must not be null"

    at Object.wrapException (http://localhost:7566/dwds/src/injected/client.js:1036:17)
    at Object.assertThrow (http://localhost:7566/dwds/src/injected/client.js:1482:15)
    at Object.boolConversionCheck (http://localhost:7566/dwds/src/injected/client.js:1478:11)
    at http://localhost:7566/dwds/src/injected/client.js:24791:21
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:7566/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:7566/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:7566/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:7566/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:7566/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:7566/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:7566/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:7566/dwds/src/injected/client.js:11956:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:7566/dwds/src/injected/client.js:11672:14)
    at Object._asyncReturn (http://localhost:7566/dwds/src/injected/client.js:3561:17)
    at http://localhost:7566/dwds/src/injected/client.js:8926:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:7566/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:7566/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:7566/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:7566/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:7566/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:7566/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:7566/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:7566/dwds/src/injected/client.js:11956:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:7566/dwds/src/injected/client.js:11672:14)
    at Object._asyncReturn (http://localhost:7566/dwds/src/injected/client.js:3561:17)
    at http://localhost:7566/dwds/src/injected/client.js:25367:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:7566/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:7566/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:7566/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:7566/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:7566/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:7566/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:7566/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:7566/dwds/src/injected/client.js:11956:9)
    at _AsyncAwaitCompleter.complete$1 (http://localhost:7566/dwds/src/injected/client.js:11672:14)
    at Object._asyncReturn (http://localhost:7566/dwds/src/injected/client.js:3561:17)
    at http://localhost:7566/dwds/src/injected/client.js:25344:24
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:7566/dwds/src/injected/client.js:3589:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:7566/dwds/src/injected/client.js:11698:12)
    at _awaitOnObject_closure.call$1 (http://localhost:7566/dwds/src/injected/client.js:11686:32)
    at StaticClosure._rootRunUnary (http://localhost:7566/dwds/src/injected/client.js:3948:18)
    at _CustomZone.runUnary$2$2 (http://localhost:7566/dwds/src/injected/client.js:13095:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:7566/dwds/src/injected/client.js:12125:51)
    at Object._Future__propagateToListeners (http://localhost:7566/dwds/src/injected/client.js:3731:93)
    at _Future._completeWithValue$1 (http://localhost:7566/dwds/src/injected/client.js:11956:9)
    at _Future__asyncCompleteWithValue_closure.call$0 (http://localhost:7566/dwds/src/injected/client.js:12059:18)
    at StaticClosure._rootRun (http://localhost:7566/dwds/src/injected/client.js:3933:16)
    at _CustomZone.run$1$1 (http://localhost:7566/dwds/src/injected/client.js:13087:39)
    at _CustomZone.runGuarded$1 (http://localhost:7566/dwds/src/injected/client.js:13030:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:7566/dwds/src/injected/client.js:13225:25)
    at Object._microtaskLoop (http://localhost:7566/dwds/src/injected/client.js:3792:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:7566/dwds/src/injected/client.js:3798:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:7566/dwds/src/injected/client.js:11575:9)
    at invokeClosure (http://localhost:7566/dwds/src/injected/client.js:1238:26)
    at MutationObserver.<anonymous> (http://localhost:7566/dwds/src/injected/client.js:1257:18)

**Comment by bkonyi** [comment]
Can you try clearing your browser cache and see if that clears this issue?

**Comment by bkonyi** [comment]
Closing due to inactivity.
