### ISSUE TITLE
Unhandled error detected in the injected client.js script

### ISSUE THREAD

**Issue by mnordine** [dart-lang/webdev#2540]
`webdev 3.7.0`, Chrome Canary 133.0.6888.0

```
TypeError: null: type 'JSNull' is not a subtype of type 'String'

    at Object.wrapException (http://127.0.0.1:55332/dwds/src/injected/client.js:1249:43)
    at Object._asString (http://127.0.0.1:55332/dwds/src/injected/client.js:2823:15)
    at main__closure7.call$1 (http://127.0.0.1:55332/dwds/src/injected/client.js:26887:54)
    at _EventStreamSubscription_closure.call$1 (http://127.0.0.1:55332/dwds/src/injected/client.js:26250:26)
    at StaticClosure._rootRunUnary (http://127.0.0.1:55332/dwds/src/injected/client.js:4365:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:55332/dwds/src/injected/client.js:14412:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:55332/dwds/src/injected/client.js:14359:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://127.0.0.1:55332/dwds/src/injected/client.js:14546:25)
    at _callDartFunctionFast1 (http://127.0.0.1:55332/dwds/src/injected/client.js:7871:25)
    at http://127.0.0.1:55332/dwds/src/injected/client.js:7847:18
```

**Comment by bkonyi** [comment]
Duplicate of https://github.com/dart-lang/webdev/issues/2553
