### ISSUE TITLE
hot restart is busteddd 

### ISSUE THREAD

**Issue by efortuna** [dart-lang/webdev#273]
This used to work with my app (earlier this week? last week? not 100% sure but it did work), but now it produces some JS that crashes:

`pub global run webdev serve --auto restart`

Using webdev alpha2 (previously used alpha1 and it worked, but I haven't tested all combinations that worked). My code is in a private repo here: https://github.com/2d-inc/dev_rpg/tree/style-sphinx-with-web-update 

```
Uncaught TypeError: Cannot read property 'Y' of null
    at Object.h6 (:8080/webdev/src/serve/injected/client.js:1096)
    at ew.ip (:8080/webdev/src/serve/injected/client.js:10628)
    at Object.eval (eval at p4 (:8080/webdev/src/serve/injected/client.js:508), <anonymous>:3:37)
    at eA.bk (:8080/webdev/src/serve/injected/client.js:5977)
    at eA.bi (:8080/webdev/src/serve/injected/client.js:6007)
    at eA.aG (:8080/webdev/src/serve/injected/client.js:6066)
    at :8080/webdev/src/serve/injected/client.js:10653
    at nm.a (:8080/webdev/src/serve/injected/client.js:1192)
    at nm.$2 (:8080/webdev/src/serve/injected/client.js:4874)
    at Object.cd (:8080/webdev/src/serve/injected/client.js:1179)
    at ew.iy (:8080/webdev/src/serve/injected/client.js:10705)
    at ew.bP (:8080/webdev/src/serve/injected/client.js:10633)
    at :8080/webdev/src/serve/injected/client.js:10528
    at nm.a (:8080/webdev/src/serve/injected/client.js:1192)
    at nm.$2 (:8080/webdev/src/serve/injected/client.js:4874)
    at n6.$1 (:8080/webdev/src/serve/injected/client.js:4866)
    at mJ.iI (:8080/webdev/src/serve/injected/client.js:5440)
    at mJ.dE (:8080/webdev/src/serve/injected/client.js:5442)
    at mi.$0 (:8080/webdev/src/serve/injected/client.js:5031)
    at Object.cM (:8080/webdev/src/serve/injected/client.js:1248)
    at R.bf (:8080/webdev/src/serve/injected/client.js:4949)
    at fD.aj (:8080/webdev/src/serve/injected/client.js:4892)
    at lC.aj (:8080/webdev/src/serve/injected/client.js:4854)
    at Object.cc (:8080/webdev/src/serve/injected/client.js:1183)
    at :8080/webdev/src/serve/injected/client.js:3439
    at nm.a (:8080/webdev/src/serve/injected/client.js:1192)
    at nm.$2 (:8080/webdev/src/serve/injected/client.js:4874)
    at n6.$1 (:8080/webdev/src/serve/injected/client.js:4866)
    at mJ.iI (:8080/webdev/src/serve/injected/client.js:5440)
    at mJ.dE (:8080/webdev/src/serve/injected/client.js:5442)
    at mi.$0 (:8080/webdev/src/serve/injected/client.js:5031)
    at Object.cM (:8080/webdev/src/serve/injected/client.js:1248)
    at ma.$0 (:8080/webdev/src/serve/injected/client.js:4997)
    at Object.uw (:8080/webdev/src/serve/injected/client.js:1276)
    at kF.uC (:8080/webdev/src/serve/injected/client.js:1278)
    at lG.$1 (:8080/webdev/src/serve/injected/client.js:4825)
    at v6 (:8080/webdev/src/serve/injected/client.js:446)
    at MutationObserver.<anonymous> (:8080/webdev/src/serve/injected/client.js:454)
client.js:372 Uncaught Instance of 'minified:p'
    at Object.b (http://localhost:8080/webdev/src/serve/injected/client.js:372:3)
    at nj.$0 (http://localhost:8080/webdev/src/serve/injected/client.js:5410:20)
    at Object.uw (http://localhost:8080/webdev/src/serve/injected/client.js:1276:5)
    at kF.uC (http://localhost:8080/webdev/src/serve/injected/client.js:1278:7)
    at lG.$1 (http://localhost:8080/webdev/src/serve/injected/client.js:4825:3)
    at v6 (http://localhost:8080/webdev/src/serve/injected/client.js:446:17)
    at MutationObserver.<anonymous> (http://localhost:8080/webdev/src/serve/injected/client.js:454:51)
b @ client.js:372
$0 @ client.js:5410
uw @ client.js:1276
uC @ client.js:1278
$1 @ client.js:4825
v6 @ client.js:446
(anonymous) @ client.js:454
childList (async)
$1 @ client.js:4832
qj @ client.js:1283
cP @ client.js:1336
nM @ client.js:1294
bW @ client.js:5344
be @ client.js:5246
bj @ client.js:5170
em @ client.js:5129
hD @ client.js:5131
(anonymous) @ client.js:488
$1 @ client.js:7795
v6 @ client.js:446
(anonymous) @ client.js:454
:8080/$sseHandler?sseClientId=f10a4b90-5970-11e9-e955-b36b266a7cbd:1 GET http://localhost:8080/$sseHandler?sseClientId=f10a4b90-5970-11e9-e955-b36b266a7cbd net::ERR_CONNECTION_REFUSED
client.js:372 Uncaught Instance of 'minified:p'
    at Object.b (http://localhost:8080/webdev/src/serve/injected/client.js:372:3)
    at nj.$0 (http://localhost:8080/webdev/src/serve/injected/client.js:5410:20)
    at Object.uw (http://localhost:8080/webdev/src/serve/injected/client.js:1276:5)
    at kF.uC (http://localhost:8080/webdev/src/serve/injected/client.js:1278:7)
    at lG.$1 (http://localhost:8080/webdev/src/serve/injected/client.js:4825:3)
    at v6 (http://localhost:8080/webdev/src/serve/injected/client.js:446:17)
    at MutationObserver.<anonymous> (http://localhost:8080/webdev/src/serve/injected/client.js:454:51)
b @ client.js:372
$0 @ client.js:5410
uw @ client.js:1276
uC @ client.js:1278
$1 @ client.js:4825
v6 @ client.js:446
(anonymous) @ client.js:454
childList (async)
$1 @ client.js:4832
qj @ client.js:1283
cP @ client.js:1336
nM @ client.js:1294
bW @ client.js:5344
be @ client.js:5246
bj @ client.js:5170
em @ client.js:5129
hD @ client.js:5131
(anonymous) @ client.js:488
$1 @ client.js:7795
v6 @ client.js:446
(anonymous) @ client.js:454
:8080/$sseHandler?sseClientId=f10a4b90-5970-11e9-e955-b36b266a7cbd:1 GET http://localhost:8080/$sseHandler?sseClientId=f10a4b90-5970-11e9-e955-b36b266a7cbd net::ERR_CONNECTION_REFUSED
client.js:372 Uncaught Instance of 'minified:p'
    at Object.b (http://localhost:8080/webdev/src/serve/injected/client.js:372:3)
    at nj.$0 (http://localhost:8080/webdev/src/serve/injected/client.js:5410:20)
    at Object.uw (http://localhost:8080/webdev/src/serve/injected/client.js:1276:5)
    at kF.uC (http://localhost:8080/webdev/src/serve/injected/client.js:1278:7)
    at lG.$1 (http://localhost:8080/webdev/src/serve/injected/client.js:4825:3)
    at v6 (http://localhost:8080/webdev/src/serve/injected/client.js:446:17)
    at MutationObserver.<anonymous> (http://localhost:8080/webdev/src/serve/injected/client.js:454:51)
b @ client.js:372
$0 @ client.js:5410
uw @ client.js:1276
uC @ client.js:1278
$1 @ client.js:4825
v6 @ client.js:446
(anonymous) @ client.js:454
childList (async)
$1 @ client.js:4832
qj @ client.js:1283
cP @ client.js:1336
nM @ client.js:1294
bW @ client.js:5344
be @ client.js:5246
bj @ client.js:5170
em @ client.js:5129
hD @ client.js:5131
(anonymous) @ client.js:488
$1 @ client.js:7795
v6 @ client.js:446
(anonymous) @ client.js:454
:8080/$sseHandler?sseClientId=f10a4b90-5970-11e9-e955-b36b266a7cbd:1 GET http://localhost:8080/$sseHandler?sseClientId=f10a4b90-5970-11e9-e955-b36b266a7cbd net::ERR_CONNECTION_REFUSED
client.js:372 Uncaught Instance of 'minified:p'
    at Object.b (http://localhost:8080/webdev/src/serve/injected/client.js:372:3)
    at nj.$0 (http://localhost:8080/webdev/src/serve/injected/client.js:5410:20)
    at Object.uw (http://localhost:8080/webdev/src/serve/injected/client.js:1276:5)
```
etc etc

**Comment by kevmoo** [comment]
Which SDK are you on?

**Comment by jakemac53** [comment]
@efortuna looks like I need to checkout out a specific branch or something for the web version?

**Comment by jakemac53** [comment]
Actually nevermind I can repro this on spinning square with kernel now also

**Comment by jakemac53** [comment]
This has something to do with the module names not lining up any more (they no longer have a `.ddc` suffix and they used to).

**Comment by efortuna** [comment]
@jakemac53 yes, and I linked to the branch you check out. ;-) (style-sphinx-with-web-update)

**Comment by efortuna** [comment]
@kevmoo 
Flutter 1.4.16 • channel dev • ssh://git@github.com/flutter/flutter.git
Framework • revision d2790bd2bb (5 days ago) • 2019-04-10 14:57:46 -0700
Engine • revision 72986c39ea
Tools • Dart 2.2.1 (build 2.2.1-dev.3.1 None)
