### ISSUE TITLE
Hot restart prints errors in terminal

### ISSUE THREAD

**Issue by nshahan** [dart-lang/webdev#293]
Repro:
webdev: 2.0.0-alpha.4
build_web_compilers: 2.0.0-alpha.2
sdk: 2.3.0-dev.0.1
Spinning square example

Edit the color of the square, save, and trigger a hot restart in devtools. There is an error printed to the terminal where webdev is running:
```
ERROR - 2019-04-17 10:55:15.501865
Asynchronous error
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
dart:convert                                                               Codec.encode
package:dwds/src/chrome_proxy_service.dart 658:30                          ChromeProxyService._chromeConsoleStreamController.<fn>.<fn>
dart:async                                                                 _EventSinkWrapper.add
package:webkit_inspection_protocol/webkit_inspection_protocol.dart 302:22  WipDomain.eventStream.<fn>.<fn>
```

**Comment by nshahan** [comment]
I just noticed this _**does not**_ happen when I run webdev with the `--auto restart` option.

**Comment by nshahan** [comment]
Also prints messages in the web consoles for the app and devtools.

App:
```
Uncaught (in promise) NoSuchMethodError: tried to call a non-function, such as null: 'method'
```

Devtools
```
main.dart.js:1116 Uncaught Unexpected error from chrome devtools:
text: Uncaught (in promise)
exception:
  description: null
  type: string
  value: NoSuchMethodError: tried to call a non-function, such as null: 'method'
attempted eval: `require("dart_sdk").developer.invokeExtension(
    "ext.flutter.inspector.getRootWidgetSummaryTree", JSON.stringify({"objectGroup":"temp_4"}));
`
 (-32603) from ext.flutter.inspector.getRootWidgetSummaryTree()
    at Object.wrapException (http://localhost:51877/main.dart.js:1116:17)
    at _rootHandleUncaughtError_closure.call$0 (http://localhost:51877/main.dart.js:19437:17)
    at Object._microtaskLoop (http://localhost:51877/main.dart.js:3750:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:51877/main.dart.js:3756:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:51877/main.dart.js:17259:9)
```

**Comment by jakemac53** [comment]
Pretty sure this is fixed by https://github.com/dart-lang/webdev/pull/311, I can't repro it
