### ISSUE TITLE
Crash with a known error should not print a stack trace

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#294]
Had a conflicting output. Got

```
[WARNING] Deleted previous snapshot due to missing asset graph.
[SEVERE] BuildDefinition: Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: web/index.html
```

And `webdev` exited. Great. Not great – the stack trace. if we terminate for a known reason, we should avoid dumping the stack – it'll just confuse users

```
[INFO] Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:51:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:129:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/serve/daemon_client.dart:16:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:27:18)
<asynchronous suspension>
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:168:24)
<asynchronous suspension>
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:115:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:111:11)
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)
#12     main (file:///Users/kevmoo/github/webdev/webdev/bin/webdev.dart:17:22)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by grouma** [comment]
Likewise we shouldn't print the stack trace if you try to listen on a port that is already used.

**Comment by jakemac53** [comment]
This looks like it will require changes in build_daemon - we currently just throw a StateError which could mean anything. We should instead make a special type of exception that is meant to be caught and handled.

**Comment by grouma** [comment]
Ahh yes. Although the port issue is thrown inside webdev.

**Comment by modulovalue** [comment]
While trying out flutter_web I came across the same exception.

```
 webdev serve -v
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 835ms
[INFO] 
[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 23.8s
[INFO] 
[INFO] Starting daemon...
[INFO] BuildDefinition: Initializing inputs
[INFO] 
[INFO] BuildDefinition: Building new asset graph...
[INFO] 
[INFO] BuildDefinition: Building new asset graph completed, took 2.1s
[INFO] 
[INFO] 
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs....
[INFO] 
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 3ms
[INFO] 
[INFO] 
[INFO] BuildDefinition: Initializing inputs
[INFO] BuildDefinition: Building new asset graph...
[INFO] BuildDefinition: Building new asset graph completed, took 2.1s
[INFO] 
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 3ms
[INFO] 
[INFO] build_runner: Setting up file watchers...
[INFO] build_runner: Setting up file watchers completed, took 6ms
[INFO] 
[INFO] 
[INFO] 
[INFO] You have hit a bug in build_runner
[INFO] Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
[INFO] 
[INFO] 
[INFO] SocketException: Failed to create server socket (OS Error: Can't assign requested address, errno = 49), address = localhost, port = 0
[INFO] dart:_http                                             HttpServer.bind
[INFO] package:shelf/shelf_io.dart 45:20                      serve
[INFO] package:build_daemon/src/server.dart 82:21             Server.listen
[INFO] package:build_daemon/src/daemon.dart 71:30             Daemon.start
[INFO] dart:async                                             _AsyncAwaitCompleter.start
[INFO] package:build_daemon/src/daemon.dart 58:21             Daemon.start
[INFO] package:build_runner/src/entrypoint/daemon.dart 74:20  DaemonCommand.run
[INFO] dart:async                                             _completeOnAsyncReturn
[INFO] package:build_runner/src/daemon/asset_server.dart      AssetServer.run
[INFO] dart:async                                             _completeOnAsyncReturn
[INFO] package:http_multi_server/http_multi_server.dart       HttpMultiServer._loopback
[INFO] 
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:52:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:142:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:24:18)
<asynchronous suspension>
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:165:24)
<asynchronous suspension>
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:110:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:111:11)
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)
#12     main (file:///Users/valauskasmodestas/.pub-cache/hosted/pub.dartlang.org/webdev-2.0.4/bin/webdev.dart:17:22)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by grouma** [comment]
I believe this issue has been addressed by @jakemac53
