### ISSUE TITLE
Opening a `--debug` app URL in another browser and hitting Alt-D crashes webdev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/webdev#295]
Ran `serve --debug`
Opened in a new chrome window. Great.

Not great: opened the app in my "normal" Chrome instance and hit `Alt-D`

Expected: a prompt or something about not being in the right Chrome instance.

Actual: got an ugly error message + stack and webdev terminated.

```
Unhandled exception:
Bad state: Could not connect to application with appInstanceId: 0063b450-5970-11e9-83ed-019000c0d304
#0      ChromeProxyService.create (package:dwds/src/chrome_proxy_service.dart:70:7)
<asynchronous suspension>
#1      DebugService.start (package:dwds/service.dart:71:55)
<asynchronous suspension>
#2      DevHandler.startDebugService (package:webdev/src/serve/handlers/dev_handler.dart:73:25)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:webdev/src/serve/handlers/dev_handler.dart:191:15)
<asynchronous suspension>
#4      DevHandler.loadAppServices.<anonymous closure> (package:webdev/src/serve/handlers/dev_handler.dart:83:24)
#5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#6      DevHandler.loadAppServices (package:webdev/src/serve/handlers/dev_handler.dart:82:24)
#7      DevHandler._handleConnection.<anonymous closure> (package:webdev/src/serve/handlers/dev_handler.dart:112:19)
<asynchronous suspension>
#8      _rootRunUnary (dart:async/zone.dart:1136:13)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1317:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by sh0umik** [comment]
Having the same problem. I tried using the latest master branch of webdev but still no luck. Works fine without `--debug` parameter. 
```
dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.1
  pedantic: ^1.0.0
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web
  webdev:
    git:
      url: https://github.com/dart-lang/webdev
      path: webdev
      ref: master
```

**Comment by jakemac53** [comment]
@sh0umik what specific error are you seeing?
