### ISSUE TITLE
Resource servers fail to start

### ISSUE THREAD

**Issue by cooler-king** [dart-lang/webdev#412]
webdev 2.0.6
Win 10 x86

Another place where `HttpMultiServer` is needed?

Rebooting clears the problem.

```[INFO] Creating build script snapshot......

[INFO] Creating build script snapshot... completed, took 12.0s
[INFO] 

[INFO] Daemon is already running.

[INFO] Registering build targets...

[INFO] Starting initial build...

[INFO] Starting resource servers...
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 7203

#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:591:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1206:26)
#2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1466:29)
#3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1457:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2520:25)
#5      HttpServer.bind (dart:_http:227:19)
#6      WebDevServer.start (package:webdev/src/serve/webdev_server.dart:81:26)
```

**Comment by jakemac53** [comment]
Looks like we need a multiserver here when the hostname is localhost https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/webdev_server.dart#L80
