### ISSUE TITLE
NoSuchMethodError: The method 'instanceRefFor' was called on null while debugging

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#574]
While debugging a Flutter for web app from flutter master, I saw the following exception from `package:dwds`:

## command

flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused lib/main.dart

## exception

NoSuchMethodError: NoSuchMethodError: The method 'instanceRefFor' was called on null.
Receiver: null
Tried calling: instanceRefFor(Instance of 'RemoteObject')

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Debugger._boundVariables.<anonymous closure> (package:dwds/src/debugging/debugger.dart:309:37)
<asynchronous suspension>
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      Future.wait (dart:async/future.dart:393:26)
#5      Debugger._boundVariables (package:dwds/src/debugging/debugger.dart:310:19)
<asynchronous suspension>
#6      Debugger._variablesFor (package:dwds/src/debugging/debugger.dart:296:54)
<asynchronous suspension>
#7      Debugger.dartFramesFor (package:dwds/src/debugging/debugger.dart:284:19)
<asynchronous suspension>
#8      Debugger._pauseHandler (package:dwds/src/debugging/debugger.dart:376:24)
<asynchronous suspension>
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#20     WipDomain.eventStream.<anonymous closure>.<anonymous closure> (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)
#21     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#22     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#28     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#29     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#30     _rootRun (dart:async/zone.dart:1120:38)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.8.5-pre.135, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.8.5-pre.135 at /Users/devoncarew/projects/flutter/flutter
    • Framework revision cd1e55b58a (26 minutes ago), 2019-08-13 15:53:54 -0700
    • Engine revision ff49ca1c6e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/devoncarew/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio/3.4/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8369
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6262.13

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (3 available)
    • iPhone Xʀ • 89AF9F3C-CCD6-444A-A6B4-44260E6E0388 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • macOS     • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G87
    • Chrome    • chrome                               • web-javascript • Google Chrome 76.0.3809.100 


! Doctor found issues in 1 category.
```

**Comment by alan-knight** [comment]
Thanks. What version of dwds are you using?

**Comment by devoncarew** [comment]
I think `0.5.0` (I'm getting my version from that used by `//packages/flutter_tools/pubspec.yaml` I believe).

**Comment by alan-knight** [comment]
Interesting. There's a dwds 0.5.0 published in pub, but no version tagged in the repo. If I look at 0.5.1 it seems very weird for inspector to be able to be null. It's a getter, and it's set up very early in the process, albeit in a weird way. Was this immediately following a reload of some sort?

**Comment by devoncarew** [comment]
I haven't seen it since the first time, and don't remember what the exact context for it was. If the resolution isn't immediately apparent, I'm fine with closing this issue; I'll re-open if I see it again.

**Comment by alan-knight** [comment]
OK.
