### ISSUE TITLE
`CodeRef.id` field not set

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#587]
We're missing an `id` field for either a `ScriptRef` or a `CodeRef` object.

```
java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsString(JsonElement.java:192)
	at org.dartlang.vm.service.element.ObjRef.getId(ObjRef.java:44)
	at io.flutter.vmService.frame.DartVmServiceStackFrame.getEqualityObject(DartVmServiceStackFrame.java:97)
```

**Comment by devoncarew** [comment]
It's for `code` field for `Frame` objects:

```
code -> {JsonObject@32738} "{"type":"@Code","id":null,"name":"build","kind":"Dart"}"
```

**Comment by devoncarew** [comment]
This is likely a blocker for debugging flutter web apps with IntelliJ; is there a milestone or label I should be applying here?
