### ISSUE TITLE
Console stack traces when invoked via `flutter run -d chrome`

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/webdev#605]
I hit this on the Flutter dev channel - on this version:

```
[vsm-macbookpro.roam.corp.google.com:/Users/vsm/flutter/flutter/examples/flutter_gallery] flutter --version
Flutter 1.9.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision c382b8e990 (4 days ago) • 2019-08-18 15:22:36 -0400
Engine • revision 5540684152
Tools • Dart 2.5.0
```

while editing `main.dart` in gallery to add config specific imports.

Trace 1
```
Performing hot restart...                                               
Dependencies graph change for module 'packages/flutter_gallery/main' detected. Dependencies was [dart_sdk,packages/flutter_gallery/foo_io,packages/flutter/src/widgets/actions,packages/flutter_gallery/gallery/app], now
[dart_sdk,packages/flutter/src/widgets/actions,packages/flutter_gallery/gallery/app]. Page can't be hot-reloaded, firing full page reload.
Unexpected Server Error WipError 6: {code: -32000, message: Execution context was destroyed.}                      
#0      DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:43:22)
<asynchronous suspension>
#1      VmService._routeRequest (package:vm_service/vm_service.dart:1730:39)
<asynchronous suspension>
#2      VmService._processRequest (package:vm_service/vm_service.dart:1707:25)
<asynchronous suspension>
#3      VmService._processMessageStr (package:vm_service/vm_service.dart:1675:9)
#4      VmService._processMessage (package:vm_service/vm_service.dart:1632:7)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
```

Trace 2

```
Performing hot restart...                                               
HotReloadFailedException (-32603) from hotRestart()             
#0      ResidentWebRunner.restart (package:flutter_tools/src/build_runner/resident_web_runner.dart:238:49)
<asynchronous suspension>
#1      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1065:61)
<asynchronous suspension>
#2      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1117:13)
<asynchronous suspension>
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
```

fyi @grouma @jonahwilliams

**Comment by jonahwilliams** [comment]
I might have fixed some of this via https://github.com/flutter/flutter/pull/38723. I think that was merged in after 1.9.0
