### ISSUE TITLE
Unhandled error detected in the injected client.js script

### ISSUE THREAD

**Issue by rednaxus** [dart-lang/webdev#625]
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

```
NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://127.0.0.1:38939/dwds/src/injected/client.js:25941:35
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:38939/dwds/src/injected/client.js:3110:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:38939/dwds/src/injected/client.js:11689:12)
    at Object._asyncStartSync (http://127.0.0.1:38939/dwds/src/injected/client.js:3075:20)
    at main__closure3.$call$body$main__closure (http://127.0.0.1:38939/dwds/src/injected/client.js:25948:16)
    at main__closure3.call$1 (http://127.0.0.1:38939/dwds/src/injected/client.js:25884:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:38939/dwds/src/injected/client.js:3393:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:38939/dwds/src/injected/client.js:13068:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:38939/dwds/src/injected/client.js:12996:14)
    at _ControllerSubscription._sendData$1 (http://127.0.0.1:38939/dwds/src/injected/client.js:12549:19)
    at _DelayedData.perform$1 (http://127.0.0.1:38939/dwds/src/injected/client.js:12756:85)
    at _StreamImplEvents.handleNext$1 (http://127.0.0.1:38939/dwds/src/injected/client.js:12830:14)
    at _PendingEvents_schedule_closure.call$0 (http://127.0.0.1:38939/dwds/src/injected/client.js:12802:10)
    at Object._microtaskLoop (http://127.0.0.1:38939/dwds/src/injected/client.js:3253:21)
    at StaticClosure._startMicrotaskLoop (http://127.0.0.1:38939/dwds/src/injected/client.js:3259:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://127.0.0.1:38939/dwds/src/injected/client.js:11565:9)
    at invokeClosure (http://127.0.0.1:38939/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://127.0.0.1:38939/dwds/src/injected/client.js:1225:18)
```

**Comment by grouma** [comment]
This isn't an issue with the package:dwds but more your environment. See this: https://github.com/dart-lang/build/issues/2337#issuecomment-513969122
