### ISSUE TITLE
Latest version of sdk, compilation failed

### ISSUE THREAD

**Issue by 6643** [dart-lang/webdev#66]
sdk
dart_2.0.0-dev.64.1-1_amd64.deb
https://github.com/dart-lang/angular/tree/master/examples/hello_world
webdev serve

**Comment by alorenzen** [comment]
Can you include the error that you got? 

There are quite a few breakages at the moment, so it would help to dedupe this to the correct one.

**Comment by 6643** [comment]
```
if@mint ~/Documents/lib/angular/examples/hello_world $ pub upgrade
Resolving dependencies... (35.6s)
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.64.1 for the following packages:

args, boolean_selector, charcode, cli_util, convert, fixnum, glob, graphs, http, http_parser, intl, io, js, logging, meta, multi_server_socket, node_preamble, package_config, plugin, pub_semver, quiver, quiver_hashcode, shelf_packages_handler, source_map_stack_trace, source_maps, source_span, stack_trace, string_scanner, term_glyph, tuple, typed_data

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
  analyzer 0.32.1
! angular 5.0.0-alpha+15 from path ../../angular (overridden)
! angular_ast 0.5.3+3 from path ../../angular_ast (overridden)
! angular_compiler 0.4.0-alpha+15 from path ../../angular_compiler (overridden)
  archive 2.0.0
  args 1.4.3
  async 2.0.7
  bazel_worker 0.1.10
  boolean_selector 1.0.3
  build 0.12.7
> build_config 0.3.1 (was 0.2.6+2)
  build_modules 0.2.3
  build_resolvers 0.2.1
> build_runner 0.9.0 (was 0.8.3)
+ build_runner_core 0.2.0
  build_test 0.10.2+5
  build_web_compilers 0.4.0+4
  built_collection 3.1.1
  built_value 5.5.2
  charcode 1.1.1
  cli_util 0.1.3
  code_builder 3.1.0
  collection 1.14.10
  convert 2.0.1
  crypto 2.0.5
  csslib 0.14.4
  dart_style 1.1.0
  fixnum 0.10.7
  front_end 0.1.1
  glob 1.1.6
  graphs 0.1.2
  html 0.13.3+1
  http 0.11.3+16
  http_multi_server 2.0.5
  http_parser 3.1.2
  intl 0.15.6
  io 0.3.2+1
  js 0.6.1
  json_annotation 0.2.9
  json_rpc_2 2.0.8
  kernel 0.3.1
  logging 0.11.3+1
  matcher 0.12.3
  meta 1.1.5
  mime 0.9.6+1
  multi_server_socket 1.0.1
  node_preamble 1.4.2
  package_config 1.0.3
  package_resolver 1.0.3
  path 1.6.1
  plugin 0.2.0+2
  pool 1.3.5
  protobuf 0.8.0 (0.9.0 available)
  pub_semver 1.4.1
+ pubspec_parse 0.1.2
  quiver 0.29.0+1
  quiver_hashcode 1.0.0
  scratch_space 0.0.3
  shelf 0.7.3+1
  shelf_packages_handler 1.0.3
  shelf_static 0.2.7+1
  shelf_web_socket 0.2.2+2
  source_gen 0.8.2
  source_map_stack_trace 1.1.4
  source_maps 0.10.5
  source_span 1.4.0
  stack_trace 1.9.2
  stream_channel 1.6.7+1
  stream_transform 0.0.14
  string_scanner 1.0.2
  term_glyph 1.0.0
  test 1.0.0
  tuple 1.0.1
  typed_data 1.1.5
  utf 0.9.0+4
  vm_service_client 0.2.4+3
  watcher 0.9.7+9
  web_socket_channel 1.0.8
  yaml 2.1.14
Warning: You are using these overridden dependencies:
! angular 5.0.0-alpha+15 from path ../../angular
! angular_ast 0.5.3+3 from path ../../angular_ast
! angular_compiler 0.4.0-alpha+15 from path ../../angular_compiler
Downloading build_test 0.10.2+5...
Downloading build_web_compilers 0.4.0+4...
Downloading build_runner 0.9.0...
Downloading tuple 1.0.1...
Downloading stack_trace 1.9.2...
Downloading source_span 1.4.0...
Downloading path 1.6.1...
Downloading meta 1.1.5...
Downloading js 0.6.1...
Downloading csslib 0.14.4...
Downloading build_config 0.3.1...
Downloading build 0.12.7...
Downloading convert 2.0.1...
Downloading build_runner_core 0.2.0...
Downloading string_scanner 1.0.2...
Downloading charcode 1.1.1...
Downloading test 1.0.0...
Downloading matcher 0.12.3...
Downloading term_glyph 1.0.0...
Downloading source_map_stack_trace 1.1.4...
Downloading stream_transform 0.0.14...
Downloading package_resolver 1.0.3...
Downloading source_maps 0.10.5...
Downloading quiver_hashcode 1.0.0...
Downloading json_annotation 0.2.9...
Downloading multi_server_socket 1.0.1...
Downloading logging 0.11.3+1...
Downloading scratch_space 0.0.3...
Downloading crypto 2.0.5...
Downloading pub_semver 1.4.1...
Downloading cli_util 0.1.3...
Downloading graphs 0.1.2...
Downloading pubspec_parse 0.1.2...
Downloading yaml 2.1.14...
Downloading shelf_static 0.2.7+1...
Downloading code_builder 3.1.0...
Downloading args 1.4.3...
Downloading build_resolvers 0.2.1...
Downloading io 0.3.2+1...
Downloading vm_service_client 0.2.4+3...
Downloading shelf_packages_handler 1.0.3...
Downloading node_preamble 1.4.2...
Downloading boolean_selector 1.0.3...
Downloading collection 1.14.10...
Downloading mime 0.9.6+1...
Downloading shelf_web_socket 0.2.2+2...
Downloading shelf 0.7.3+1...
Downloading http_parser 3.1.2...
Downloading source_gen 0.8.2...
Downloading glob 1.1.6...
Downloading pool 1.3.5...
Downloading http_multi_server 2.0.5...
Downloading typed_data 1.1.5...
Downloading analyzer 0.32.1...
Downloading kernel 0.3.1...
Downloading front_end 0.1.1...
Downloading package_config 1.0.3...
Downloading plugin 0.2.0+2...
Downloading build_modules 0.2.3...
Downloading bazel_worker 0.1.10...
Downloading protobuf 0.8.0...
Downloading dart_style 1.1.0...
Downloading watcher 0.9.7+9...
Downloading fixnum 0.10.7...
Downloading async 2.0.7...
Downloading stream_channel 1.6.7+1...
Downloading json_rpc_2 2.0.8...
Downloading intl 0.15.6...
Downloading web_socket_channel 1.0.8...
Downloading html 0.13.3+1...
Downloading utf 0.9.0+4...
Downloading built_value 5.5.2...
Downloading built_collection 3.1.1...
Downloading archive 2.0.0...
Downloading http 0.11.3+16...
Downloading quiver 0.29.0+1...
Changed 4 dependencies!
Precompiling executables... (23.2s)
Precompiled build_runner:graph_inspector.
Precompiled build_runner:build_runner.
if@mint ~/Documents/lib/angular/examples/hello_world $ webdev serve
Crash when formatting: [NonAsciiIdentifier] The non-ASCII character 'ƽ' (U+01BD) can't be used in identifiers, only in strings and comments.
RangeError (index): Invalid value: Not in range 0..268600, inclusive: 268740
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Crash when compiling file:///home/if/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot,
at character offset 266817:
RangeError (index): Invalid value: Not in range 0..268600, inclusive: 268740
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```

**Comment by alorenzen** [comment]
Yup, this is https://github.com/dart-lang/pub/issues/1932.
