### ISSUE TITLE
flutter_web error,unable open chromer

### ISSUE THREAD

**Issue by jinyuanqing** [dart-lang/webdev#678]
[INFO] Running build completed, took 367ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 214ms
[INFO] Succeeded after 589ms with 0 outputs (0 actions)
[INFO] Debug service listening on ws://127.0.0.1:50633/LDVId0cYFIY=
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://127.0.0.1:50597/dwds/src/injected/client.js:26055:35
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:50597/dwds/src/injected/client.js:3110:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:50597/dwds/src/injected/client.js:11704:12)
    at Object._asyncStartSync (http://127.0.0.1:50597/dwds/src/injected/client.js:3075:20)
    at main__closure3.$call$body$main__closure (http://127.0.0.1:50597/dwds/src/injected/client.js:26063:16)

**Comment by jakemac53** [comment]
Can you confirm your webdev version is up do date? What does `webdev --version` print out?

**Comment by jinyuanqing** [comment]
thank you,i solve the problem
