### ISSUE TITLE
Unhandled error detected in the injected client.js script

### ISSUE THREAD

**Issue by rubansiva384** [dart-lang/webdev#688]
NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://127.0.0.1:8080/dwds/src/injected/client.js:26253:35
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3107:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11692:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3072:20)
    at main__closure3.$call$body$main__closure (http://127.0.0.1:8080/dwds/src/injected/client.js:26265:16)
    at main__closure3.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:26191:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:3396:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:13124:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:13052:14)
    at _ControllerSubscription._sendData$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:12535:19)
    at _DelayedData.perform$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:12742:85)
    at _StreamImplEvents.handleNext$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:12816:14)
    at _PendingEvents_schedule_closure.call$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:12788:10)
    at Object._microtaskLoop (http://127.0.0.1:8080/dwds/src/injected/client.js:3257:21)
    at StaticClosure._startMicrotaskLoop (http://127.0.0.1:8080/dwds/src/injected/client.js:3263:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11583:9)
    at invokeClosure (http://127.0.0.1:8080/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://127.0.0.1:8080/dwds/src/injected/client.js:1225:18)

**Comment by jakemac53** [comment]
@rubansiva384 can you confirm you are on the latest webdev? You can update by running `pub global activate webdev` again.

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/725
