### ISSUE TITLE
"Can only perform operation while paused" when trying to resume after starting paused

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#716]
Slightly related to https://github.com/dart-lang/webdev/issues/629 - I'm trying to test the start-paused functionality being added in Flutter (https://github.com/flutter/flutter/pull/42144), but although the isolate now has a pauseEvent kind of `PauseStart`, it throws this error when trying to resume:

```
WipError 10: {code: -32000, message: Can only perform operation while paused.}
#0      Debugger.resume (package:dwds/src/debugging/debugger.dart:136:16)
<asynchronous suspension>
#1      ChromeProxyService.resume (package:dwds/src/services/chrome_proxy_service.dart:393:17)
<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1105:51)
<asynchronous suspension>
```

Here's the full log of communication between VS Code and the debugger:

[Dart-Code-Log-2019-09-02 09-11-52.txt](https://github.com/dart-lang/webdev/files/3701416/Dart-Code-Log-2019-09-02.09-11-52.txt)

**Comment by DanTup** [comment]
Looking at the code, this might be coming from Chrome's debugger? In which case the issue might be that suppressing calling `main` doesn't leave the Chrome debugger in a paused state?

https://github.com/dart-lang/webdev/blob/65fd8e10b64c9d53567bf70f79d4331d2eb9ce1e/dwds/lib/src/debugging/debugger.dart#L136

This also means Flutter doesn't see the resume event, and therefore doesn't call `main` later.

**Comment by DanTup** [comment]
Had a quick test, and fix looks good - in VS Code I'm no longer seeing errors and I'm hitting breakpoints - thanks! :-)
