### ISSUE TITLE
injected-client not allowing to load the web  

### ISSUE THREAD

**Issue by MuhammamdArslanKhan** [dart-lang/webdev#725]
The project was working fine but suddenly it stop loading web app.
Here is output log

``` 
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 555ms
[INFO]
[INFO] Starting daemon...
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 423ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.5s
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 423ms
[INFO]
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.5s
[INFO]
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 9ms
[INFO]
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving DevTools at http://127.0.0.1:17123
[INFO] Serving `web` on http://127.0.0.1:17123
[INFO] About to build [web]...
[INFO] Running build...
[INFO] Running build completed, took 780ms
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 259ms
[INFO] Succeeded after 1.1s with 0 outputs (0 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Debug service listening on ws://127.0.0.1:17123/AXyabey6Hdc=
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://localhost:57460/dwds/src/injected/client.js:26253:35
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:57460/dwds/src/injected/client.js:3107:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:57460/dwds/src/injected/client.js:11692:12)
    at Object._asyncStartSync (http://localhost:57460/dwds/src/injected/client.js:3072:20)
    at main__closure3.$call$body$main__closure (http://localhost:57460/dwds/src/injected/client.js:26265:16)
    at main__closure3.call$1 (http://localhost:57460/dwds/src/injected/client.js:26191:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57460/dwds/src/injected/client.js:3396:16)
    at _CustomZone.runUnary$2$2 (http://localhost:57460/dwds/src/injected/client.js:13124:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57460/dwds/src/injected/client.js:13052:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57460/dwds/src/injected/client.js:12535:19)
    at _DelayedData.perform$1 (http://localhost:57460/dwds/src/injected/client.js:12742:85)
    at _StreamImplEvents.handleNext$1 (http://localhost:57460/dwds/src/injected/client.js:12816:14)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:57460/dwds/src/injected/client.js:12788:10)
    at Object._microtaskLoop (http://localhost:57460/dwds/src/injected/client.js:3257:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:57460/dwds/src/injected/client.js:3263:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:57460/dwds/src/injected/client.js:11583:9)
    at invokeClosure (http://localhost:57460/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://localhost:57460/dwds/src/injected/client.js:1225:18)
```

**Comment by grouma** [comment]
What version of `webdev` are you using? What's your environment like, e.g. Chrome, Linux etc?

**Comment by enyo** [comment]
I'm having the same issue. Running on macOS, same issue on Chrome as on Safari.

```
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'cast$2$0' on null
TypeError: Cannot read property 'cast$2$0' of null
    at Object.cast$2$0$ax (http://localhost:8080/dashboard/dwds/src/injected/client.js:2795:43)
    at http://localhost:8080/dashboard/dwds/src/injected/client.js:24184:49
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/dashboard/dwds/src/injected/client.js:3003:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/dashboard/dwds/src/injected/client.js:10800:12)
    at _awaitOnObject_closure.call$1 (http://localhost:8080/dashboard/dwds/src/injected/client.js:10786:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:8080/dashboard/dwds/src/injected/client.js:3299:18)
    at _CustomZone.runUnary$2$2 (http://localhost:8080/dashboard/dwds/src/injected/client.js:12130:182)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:8080/dashboard/dwds/src/injected/client.js:11178:61)
    at Object._Future__propagateToListeners (http://localhost:8080/dashboard/dwds/src/injected/client.js:3114:104)
    at _Future._completeWithValue$1 (http://localhost:8080/dashboard/dwds/src/injected/client.js:11008:9)
    at _Future__asyncComplete_closure.call$0 (http://localhost:8080/dashboard/dwds/src/injected/client.js:11101:10)
    at StaticClosure._rootRun [as call$1$4] (http://localhost:8080/dashboard/dwds/src/injected/client.js:3284:16)
    at _CustomZone.run$1$1 (http://localhost:8080/dashboard/dwds/src/injected/client.js:12121:158)
    at _CustomZone.runGuarded$1 (http://localhost:8080/dashboard/dwds/src/injected/client.js:12046:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:8080/dashboard/dwds/src/injected/client.js:12302:25)
    at Object._microtaskLoop (http://localhost:8080/dashboard/dwds/src/injected/client.js:3168:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:8080/dashboard/dwds/src/injected/client.js:3174:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:8080/dashboard/dwds/src/injected/client.js:10675:9)
    at invokeClosure (http://localhost:8080/dashboard/dwds/src/injected/client.js:1188:26)
    at MutationObserver.<anonymous> (http://localhost:8080/dashboard/dwds/src/injected/client.js:1207:18)
```

```
% webdev --version
2.5.4
```

**Comment by grouma** [comment]
Do you have a minimal repo you can share to help diagnose issues?

**Comment by enyo** [comment]
I have since realized that the problem is most likely due to my app being proxied through a dart http server that I wrote. Apparently that doesn't work?

**Comment by grouma** [comment]
It should work with a proxy. Just make sure the requests from the injected client make it through:
https://github.com/dart-lang/webdev/blob/master/dwds/web/reloader/require_restarter.dart#L133

**Comment by enyo** [comment]
Thanks @grouma will check it out!
