### ISSUE TITLE
"Invalid null response from service" when calling addBreakpointWithScriptUri

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#740]
I have some code trying to set a breakpoint on line 0 - I think this is an error (I think for Dart they should be 1-based?), however the response seems incorrect. It should return something like a "102 (Cannot add breakpoint)", but it throws this error instead.

**Edit:** Happens on `line: 1` too, so maybe it's just for all invalid locations?

```
==> {"id":"472","method":"resume","params":{"isolateId":"1"}}
<== {"jsonrpc":"2.0","result":{"type":"Success"},"id":"472"}
==> {"id":"473","method":"removeBreakpoint","params":{"isolateId":"1","breakpointId":"1"}}
<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointRemoved","timestamp":1571311399782,"isolate":{"type":"@Isolate","id":"1","number":"1","name":"http://localhost:63027/:main()"},"breakpoint":{"type":"Breakpoint","id":"1","breakpointNumber":null,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","id":"474","uri":"package:hello_world/main.dart"},"tokenPos":1439}}}}}
<== {"jsonrpc":"2.0","result":{"type":"Success"},"id":"473"}
<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","timestamp":1571311399784,"isolate":{"type":"@Isolate","id":"1","number":"1","name":"http://localhost:63027/:main()"}}}}
==> {"id":"474","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/dantup/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/lib/main.dart","line":0}}
==> {"id":"475","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/dantup/Dev/Dart-Code/src/test/test_projects/flutter_hello_world/lib/main.dart","line":48}}
<== {"jsonrpc":"2.0","error":{"code":-32603,"message":"Bad state: Invalid null response from service/*SNIP*/\n"},"id":"474"}

[Error] Bad state: Invalid null response from service
#0      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1202:9)
<asynchronous suspension>
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#15     _StreamController._add (dart:async/stream_controller.dart:640:7)
#16     _StreamController.add (dart:async/stream_controller.dart:586:5)
#17     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#26     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#34     _StreamController._add (dart:async/stream_controller.dart:640:7)
#35     _StreamController.add (dart:async/stream_controller.dart:586:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#37     _rootRunUnary (dart:async/zone.dart:1136:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#43     _StreamController._add (dart:async/stream_controller.dart:640:7)
#44     _StreamController.add (dart:async/stream_controller.dart:586:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
[12:23:19 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","result":{"type":"Breakpoint","id":"2","breakpointNumber":null,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","id":"474","uri":"package:hello_world/main.dart"},"tokenPos":1439}},"id":"475"}
```

**Comment by grouma** [comment]
We'll have to take a look but I think we generally just throw if we can't set a breakpoint.

**Comment by DanTup** [comment]
There's a specific error code for this in the VM service spec - it'd be good to keep these the same if possible (I'm not currently doing anything special based on it right now, but I do have some outstanding breakpoint issues that might mean tightening up on this).
