### ISSUE TITLE
Support evaluateInFrame in debug proxy

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#742]
`evaluateInFrame` is used a lot in VS Code (and probably IntelliJ), but currently it just throws an `UnimplementedException`.

```
==> {
	"id": "25",
	"method": "evaluateInFrame",
	"params": {
		"disableBreakpoints": true,
		"expression": "[0][0]",
		"frameIndex": 0,
		"isolateId": "1"
	}
}
<== {
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "UnimplementedError
		#0      ChromeProxyService.evaluateInFrame (package:dwds/src/services/chrome_proxy_service.dart:246:5)
		#1      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:972:51)..."
	},
	"id": "25"
}
```

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/715

**Comment by DanTup** [comment]
Whoops, I somehow didn't find that 🙈 thanks!
