### ISSUE TITLE
Error: Type 'List<dynamic>'

### ISSUE THREAD

**Issue by davidg88007** [dart-lang/webdev#746]
Beginner, attempting to deserialize some json, which is a list of Node.
Following the code in https://github.com/google/built_value.dart/blob/master/built_value/test/built_list_serializer_test.dart
```
    var specifiedType = const FullType(BuiltList, [FullType(Node)]);
    var updatedSerializers = (serializers.toBuilder()
      ..addBuilderFactory(specifiedType, () => ListBuilder<Node>()))
        .build();

    List<Map<String, dynamic>> aMapList = json.decode(jsonString);
    List<Node> nodes = updatedSerializers.deserialize(aMapList, specifiedType: specifiedType);
```

```
Error: Type 'List<dynamic>' should be 'List<Map<String, dynamic>>' to implement expected type 'List<Map<String, dynamic>>'.
Error: Type 'List<dynamic>' should be 'List<Map<String, dynamic>>' to implement expected type 'List<Map<String, dynamic>>'.
    at Object.throw_ [as throw] (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:3868:11)
    at Object.castError (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:3828:15)
    at Object.cast [as as] (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:4150:17)
    at Function.check_C [as _check] (http://localhost:53322/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:3800:19)
    at new main.NetworkViewer.new (http://localhost:53322/data_model.ddc.js:168:48)
    at main$ (http://localhost:53322/data_model.ddc.js:186:5)
    at Function.call$0 (http://localhost:53322/dwds/src/injected/client.js:28012:16)
    at http://localhost:53322/dwds/src/injected/client.js:26365:35
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53322/dwds/src/injected/client.js:3111:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53322/dwds/src/injected/client.js:11691:12)
    at Object._asyncStartSync (http://localhost:53322/dwds/src/injected/client.js:3076:20)
    at main__closure1.$call$body$main__closure (http://localhost:53322/dwds/src/injected/client.js:26377:16)
    at main__closure1.call$1 (http://localhost:53322/dwds/src/injected/client.js:26303:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53322/dwds/src/injected/client.js:3400:16)
    at _CustomZone.runUnary$2$2 (http://localhost:53322/dwds/src/injected/client.js:13123:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53322/dwds/src/injected/client.js:13051:14)
    at _ControllerSubscription._sendData$1 (http://localhost:53322/dwds/src/injected/client.js:12534:19)
    at _DelayedData.perform$1 (http://localhost:53322/dwds/src/injected/client.js:12741:85)
    at _StreamImplEvents.handleNext$1 (http://localhost:53322/dwds/src/injected/client.js:12815:14)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:53322/dwds/src/injected/client.js:12787:10)
    at Object._microtaskLoop (http://localhost:53322/dwds/src/injected/client.js:3261:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:53322/dwds/src/injected/client.js:3267:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:53322/dwds/src/injected/client.js:11582:9)
    at invokeClosure (http://localhost:53322/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://localhost:53322/dwds/src/injected/client.js:1225:18)
```

**Comment by jakemac53** [comment]
In the future please go through stackoverflow, gitter, or other support channels for this type of issue, as this is not a support forum.

Specifically here you will need to cast your list to a list of the specific type you need, using the `.cast` method. Something like `(json.decode(jsonString) as List).cast<Map<String, dynamic>>();`.
