### ISSUE TITLE
Unhandled error detected in the injected client.js script

### ISSUE THREAD

**Issue by njohnson-una** [dart-lang/webdev#763]
I have received the following error message when attempting to load a development page served by angular dart (using webdev serve).  I have tried running 'pub global activate webdev' which activated webdev 2.5.3 (from 2.5.2), but still receive exactly the same issue.

Any help is appreciated.  Thank you!

Error message from javascript console (Chrome Version 77.0.3865.90):

Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://localhost:8080/dwds/src/injected/client.js:26365:35
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/dwds/src/injected/client.js:3111:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/dwds/src/injected/client.js:11691:12)
    at Object._asyncStartSync (http://localhost:8080/dwds/src/injected/client.js:3076:20)
    at main__closure1.$call$body$main__closure (http://localhost:8080/dwds/src/injected/client.js:26377:16)
    at main__closure1.call$1 (http://localhost:8080/dwds/src/injected/client.js:26303:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:8080/dwds/src/injected/client.js:3400:16)
    at _CustomZone.runUnary$2$2 (http://localhost:8080/dwds/src/injected/client.js:13123:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:8080/dwds/src/injected/client.js:13051:14)
    at _ControllerSubscription._sendData$1 (http://localhost:8080/dwds/src/injected/client.js:12534:19)
    at _DelayedData.perform$1 (http://localhost:8080/dwds/src/injected/client.js:12741:85)
    at _StreamImplEvents.handleNext$1 (http://localhost:8080/dwds/src/injected/client.js:12815:14)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:8080/dwds/src/injected/client.js:12787:10)
    at Object._microtaskLoop (http://localhost:8080/dwds/src/injected/client.js:3261:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:8080/dwds/src/injected/client.js:3267:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:8080/dwds/src/injected/client.js:11582:9)
    at invokeClosure (http://localhost:8080/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://localhost:8080/dwds/src/injected/client.js:1225:18)

**Comment by njohnson-una** [comment]
I was able to bypass by removing the .dart_tool directory from the project.  Does that mean this was caused by some residual artifacts from a previous build?  Is there a command to clear these artifacts or is removing the .dart_tool directory the best way to accomplish that?

**Comment by jakemac53** [comment]
You can use `pub run build_runner clean` to remove build artifacts.

**Comment by njohnson-una** [comment]
Very good to know, thank you!

**Comment by grouma** [comment]
Took a look. The error is coming from this line:

``` JS
self.$dartRunMain.call$0();
```

This means for some odd reason that the main function as compiled by `build_web_compilers` is not defined. It's quite odd that a build cache clean would resolve this issue.

@njohnson-una when this issue occurred did you have any console errors? Could it be that we are trying to do a reload on a broken application?

**Comment by njohnson-una** [comment]
Please let me know if I'm not answering in sufficient detail.

I believe the only chrome console logs I saw were the error message reproduced above and a message or two like the following (this appears on successful loads as well):

[Violation] 'load' handler took 584ms

I am certain the build succeeded in the 'webdev serve' window.  I did ctrl-c and tried a second time because of this issue.  I also tried the localhost url and then a shift-refresh in case that would reload something stale (likely not, but I tried it anyway).

The networking tab showed that only about 10-15 requests were completed (I didn't screenshot that) when usually it's hundreds.  I assumed this was because of the error in the chrome console tab.

**Comment by grouma** [comment]
That's the detail I was looking for, thanks! Unfortunately I don't know what's going on but that will help diagnose.
