### ISSUE TITLE
"The getter 'appConnection' was called on null" when resuming via debug proxy

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#771]
I don't have a repro for this, but it showed up in the logs while I was running tests. If I find a way to repro it, I'll post back - but I figured it might be clear from the code/stack what's happened (and if not, it might be possible to improve the error to make it easier if it crops up again).

I'm running using dwds from master today, via Flutter (also latest master, with Jonah's start-paused changes merged and using dwds with a dependency_override).

```
-32603 NoSuchMethodError: The getter 'appConnection' was called on null.
Receiver: null
Tried calling: appConnection
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ChromeProxyService.resume (package:dwds/src/services/chrome_proxy_service.dart:418:20)
<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1105:51)
<asynchronous suspension>
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#9      _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#17     _StreamController._add (dart:async/stream_controller.dart:640:7)
#18     _StreamController.add (dart:async/stream_controller.dart:586:5)
#19     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#28     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#36     _StreamController._add (dart:async/stream_controller.dart:640:7)
#37     _StreamController.add (dart:async/stream_controller.dart:586:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#39     _rootRunUnary (dart:async/zone.dart:1136:13)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#44     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#45     _StreamController._add (dart:async/stream_controller.dart:640:7)
#46     _StreamController.add (dart:async/stream_controller.dart:586:5)
#47     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#48     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#49     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#50     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#51     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by jakemac53** [comment]
Ya we get a lot of race condition type bugs like this due to various factors - its worth us trying to handle them more gracefully because they can result in flutter_tool crashes etc.

**Comment by grouma** [comment]
@DanTup is this still an issue?

**Comment by DanTup** [comment]
I haven't seen it and it's not in the logs after running my tests now, though from the description above it seems like a race. If you can call this `resume()` here after `appConnection` has been set to `null`, I presume it would still occur (if it's not being handled somewhere else):

https://github.com/dart-lang/webdev/blob/58664d4d72555dfc6aaf04030afe005eefb65cb5/dwds/lib/src/services/chrome_proxy_service.dart#L565
