### ISSUE TITLE
Invalid argument (objectId): No objectId found: Instance(length:12) of '_GrowableList' when calling getObject

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#772]
In VS Code we call `toString()` on objects to show in places like the Variables list. We previously used `evaluate` but since that doesn't currently work here (only for `targetId`s that are libraries) I've tried moving it over to invoke (which based on #591 I believe IntelliJ is using too).

It works for some objects, but others I get errors like this:

```
Invalid argument (objectId): No objectId found: Instance(length:12) of '_GrowableList'
#0      dartIdFor (package:dwds/src/utilities/conversions.dart:103:3)
#1      _primitiveInstance (package:dwds/src/debugging/instance.dart:24:43)
#2      InstanceHelper._instanceRefForRemote (package:dwds/src/debugging/instance.dart:271:18)
<asynchronous suspension>
#3      InstanceHelper.instanceRefFor (package:dwds/src/debugging/instance.dart:237:12)
#4      InstanceHelper._mapAssociations (package:dwds/src/debugging/instance.dart:150:25)
<asynchronous suspension>
#5      InstanceHelper._mapInstanceFor (package:dwds/src/debugging/instance.dart:159:30)
<asynchronous suspension>
#6      InstanceHelper.instanceFor (package:dwds/src/debugging/instance.dart:85:20)
<asynchronous suspension>
#7      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:310:24)
<asynchronous suspension>
#8      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:300:19)
#9      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
<asynchronous suspension>
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
```

Here's the request I sent:

```js
{
	"id": "487",
	"method": "getObject",
	"params": {
		"isolateId": "1",
		"objectId": "{\"injectedScriptId\":1,\"id\":1364}"
	}
}
```

And here's the `BoundVariable` I saw in the stack that led to it:

```js
{
	"type": "BoundVariable",
	"name": "m",
	"value": {
		"type": "@Instance",
		"id": "{\"injectedScriptId\":1,\"id\":1364}",
		"kind": "Map",
		"class": {
			"type": "@Class",
			"id": "dart:_js_helper:LinkedMap",
			"name": "LinkedMap<Object, Object>"
		},
		"valueAsStringIsTruncated": false,
		"length": 10
	},
	"declarationTokenPos": -1,
	"scopeStartTokenPos": null,
	"scopeEndTokenPos": null
}
```

**Comment by alan-knight** [comment]
I can reproduce this with a Map whose value is a List.

**Comment by alan-knight** [comment]
#779 should fix this. The problem is that we were trying to get the map associations in a single round-trip, so returning a list by value. But then if there are keys or values in that Map which are serializable from JavaScript (e.g. a List of int) then we will get that by value as well, rather than as a RemoteObject. So we need to do it in a more roundabout way.

**Comment by DanTup** [comment]
Yep, seems to work great now - thanks!
