### ISSUE TITLE
"Bad state: Future already completed" when sending app.stop to daemon

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#774]
Note: This is using the webdev daemon, not Flutter. This is low priority to me (assuming it's specific to the daemon and not Flutter's use of dwds), but I was merging some work that was running the tests for it so I thought I should raise it - this code will likely become the non-Flutter web support in VS Code (assuming the current daemon protocol isn't replaced before I do it).

My test sent an `app.stop` to the daemon and I ended up with this duplicate-completion error in some dwds dispose code written to `stderr` (there was also a `disposed` error in response to an in-progress `callServiceExtension` request too but that one seems reasonable - the in-flight requests are going to fail somehow if I ask for the app to be stopped).

```
[3:29:02 PM] [Observatory] [Info] Disconnect requested!
[3:29:02 PM] [WebDaemon] [Info] ==> [{"id":"2","method":"app.stop","params":{"appId":"bdQaa468Vk7EKtRey+xqJg=="}}]
[3:29:02 PM] [WebDaemon] [Info] <== [{"event":"app.log","params":{"appId":"bdQaa468Vk7EKtRey+xqJg==","log":"package:flutter_web/src/widgets/framework.dart 3935:15  performRebuild\n"}}]
[3:29:02 PM] [WebDaemon] [Info] <== [{"event":"app.log","params":{"appId":"bdQaa468Vk7EKtRey+xqJg==","log":"Lost connection to device."}}]
[3:29:02 PM] [WebDaemon] [Info] <== [{"event":"app.stop","params":{"appId":"bdQaa468Vk7EKtRey+xqJg=="}}]
[3:29:02 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceUnregistered","timestamp":null,"service":"hotRestart","method":"hotRestart"}}}
[3:29:02 PM] [WebDaemon] [Info] <== [{"id":"1","error":"disposed","trace":"#0      AppDomain._callServiceExtension (package:webdev/src/daemon/app_domain.dart:132:9)
<asynchronous suspension>
#1      Domain.handleCommand.<anonymous closure> (package:webdev/src/daemon/domain.dart:27:68)
#2      new Future.sync (dart:async/future.dart:222:31)
#3      Domain.handleCommand (package:webdev/src/daemon/domain.dart:25:77)
#4      Daemon._handleRequest (package:webdev/src/daemon/daemon.dart:67:26)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
...
"}]
[3:29:02 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceUnregistered","timestamp":null,"service":"fullReload","method":"fullReload"}}}
[3:29:02 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceUnregistered","timestamp":null,"service":"ext.dwds.screenshot","method":"ext.dwds.screenshot"}}}
[3:29:02 PM] [WebDaemon] [Error] Unhandled exception:
Bad state: Future already completed
#0      _Completer.completeError (dart:async/future_impl.dart:21:31)
#1      VmService.dispose.<anonymous closure> (package:vm_service/vm_service.dart:1688:41)
#2      Iterable.forEach (dart:core/iterable.dart:277:30)
#3      VmService.dispose (package:vm_service/vm_service.dart:1688:24)
#4      DwdsVmClient.close (package:dwds/src/dwds_vm_client.dart:25:12)
<asynchronous suspension>
#5      AppDebugServices.close (package:dwds/src/services/app_debug_services.dart:27:55)
#6      DebugConnection.close (package:dwds/src/connections/debug_connection.dart:38:29)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      DebugConnection.close (package:dwds/src/connections/debug_connection.dart:35:21)
#9      AppDomain.dispose (package:webdev/src/daemon/app_domain.dart:189:23)
#10     Daemon.shutdown (package:webdev/src/daemon/daemon.dart:83:14)
#11     AppDomain._initialize.<anonymous closure> (package:webdev/src/daemon/app_domain.dart:77:16)
#12     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by grouma** [comment]
@DanTup is this still an issue?

**Comment by DanTup** [comment]
I can't repro this using latest published packages:

```
[11:14:44 AM] [VmService] [Info] [Dart] Termination requested!
[11:14:44 AM] [WebDaemon] [Info] [Dart] ==> [{"id":"1","method":"app.stop","params":{"appId":"h8Z3IK6thycKYGQbL5007w=="}}]
[11:14:44 AM] [VmService] [Info] [Dart] VM service connection closed: 1005 ()
[11:14:44 AM] [WebDaemon] [Info] [Dart] <== [{"event":"app.log","params":{"appId":"h8Z3IK6thycKYGQbL5007w==","log":"Lost connection to device."}}]
[11:14:44 AM] [WebDaemon] [Info] [Dart] <== [{"event":"app.stop","params":{"appId":"h8Z3IK6thycKYGQbL5007w=="}}]
[11:14:44 AM] [WebDaemon] [Info] [Dart] <== [{"id":"1","result":true}]
[11:14:44 AM] [WebDaemon] [Info] [Dart] <== [{"event":"daemon.log","params":{"log":"[INFO] Stopped debug service on ws://127.0.0.1:53163\n"}}]
[11:14:44 AM] [WebDaemon] [Info] [Dart] Process terminated! 0, null
[11:14:44 AM] [VmService] [Info] [Dart] Process exited (0)
```
