### ISSUE TITLE
Fail on a simple new project

### ISSUE THREAD

**Issue by rafante** [dart-lang/webdev#780]
`Launching lib/main.dart on Chrome in debug mode...
Building application for the web...                                17,9s
Attempting to connect to browser instance..                         4,0s

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web.

🔥  To hot restart (and rebuild state), press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:50369/A0L12hzXBl4=
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at
https://github.com/dart-lang/webdev/issues/new and attach this output:

NoSuchMethodError: method not found: 'call$0' on null
TypeError: Cannot read property 'call$0' of undefined
    at http://localhost:50327/dwds/src/injected/client.js:26365:35
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:50327/dwds/src/injected/client.js:3111:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:50327/dwds/src/injected/client.js:11691:12)
    at Object._asyncStartSync (http://localhost:50327/dwds/src/injected/client.js:3076:20)
    at main__closure1.$call$body$main__closure (http://localhost:50327/dwds/src/injected/client.js:26377:16)
    at main__closure1.call$1 (http://localhost:50327/dwds/src/injected/client.js:26303:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:50327/dwds/src/injected/client.js:3400:16)
    at _CustomZone.runUnary$2$2 (http://localhost:50327/dwds/src/injected/client.js:13123:182)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:50327/dwds/src/injected/client.js:13051:14)
    at _ControllerSubscription._sendData$1 (http://localhost:50327/dwds/src/injected/client.js:12534:19)
    at _DelayedData.perform$1 (http://localhost:50327/dwds/src/injected/client.js:12741:85)
    at _StreamImplEvents.handleNext$1 (http://localhost:50327/dwds/src/injected/client.js:12815:14)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:50327/dwds/src/injected/client.js:12787:10)
    at Object._microtaskLoop (http://localhost:50327/dwds/src/injected/client.js:3261:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:50327/dwds/src/injected/client.js:3267:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:50327/dwds/src/injected/client.js:11582:9)
    at invokeClosure (http://localhost:50327/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://localhost:50327/dwds/src/injected/client.js:1225:18)`

I created a simple project, it worked. Then I removed the standard comments and set the primary color from blue to green, and that error sstarted. Tried to restart, but nothing different happens:
There's the flutter doctor down below

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.163, on Mac OS X 10.13.6 17G5019, locale pt-BR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.`

**Comment by grouma** [comment]
Is this still a problem on the latest version of Flutter?

We have addressed many issues in the last couple of weeks. For future reference Flutter Web issues should be opened here:
https://github.com/flutter/flutter/issues
