### ISSUE TITLE
package:dwds should allow setting multiple breakpoints at the same line

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#782]
IntelliJ will often send in multiple VM breakpoints per user breakpoint, in order to handle the case where a script might be running from different urls (file:, package:, ...).

The VM impl of the service protocol supports this (cc @bkonyi to confirm). When IntelliJ does this w/ flutter web apps however, we get an error back from package:dwds:

```
==> {"jsonrpc":"2.0","id":"44","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"package:foo_flutter/main.dart","line":9}}
```

```
<== {"jsonrpc":"2.0","error":{"code":-32603,"message":"WipError 10: {code: -32000, message: Breakpoint at specified location already exists.}
#0      Debugger._setBreakpoint (package:dwds/src/debugging/debugger.dart:319:9)
<asynchronous suspension>
#1      Debugger.addBreakpoint (package:dwds/src/debugging/debugger.dart:266:32)
<asynchronous suspension>
#2    ...
```

As an aside, when the `addBreakpointWithScriptUri` call fails, the service protocol's spec says it should fail w/ a 102 error code:

```
If no breakpoint is possible at that line, the _102_ (Cannot add breakpoint) error code is returned.
```

This call currently fails w/ an `-32603` error.

**Comment by devoncarew** [comment]
Some more detail on the service protocol traffic:

```
==> {"jsonrpc":"2.0","id":"41","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/devoncarew/IdeaProjects/foo_flutter/lib/main.dart","line":56}}
```

```
==> {"jsonrpc":"2.0","id":"42","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"package:foo_flutter/main.dart","line":56}}
```

```
<== {"jsonrpc":"2.0","result":{"type":"Breakpoint","id":"3","breakpointNumber":null,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","id":"474","uri":"package:foo_flutter/main.dart"},"tokenPos":1359}},"id":"41"}
```

```
<== {"jsonrpc":"2.0","error":{"code":-32603,"message":"WipError 102: {code: -32000, message: Breakpoint at specified location already exists.}
#0      Debugger._setBreakpoint (package:dwds/src/debugging/debugger.dart:319:9)
<asynchronous suspension>
#1      Debugger.addBreakpoint (package:dwds/src/debugging/debugger.dart:266:32)
<asynchronous suspension>
#2      ChromeProxyService.addBreakpointWithScriptUri (package:dwds/src/services/chrome_proxy_service.dart:223:10)
<asynchronous suspension>
#3      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:932:51)
<asynchronous suspension>
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#10     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#17     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#18     _StreamController._add (dart:async/stream_controller.dart:640:7)
#19     _StreamController.add (dart:async/stream_controller.dart:586:5)
#20     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#29     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#37     _StreamController._add (dart:async/stream_controller.dart:640:7)
#38     _StreamController.add (dart:async/stream_controller.dart:586:5)
#39     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#40     _rootRunUnary (dart:async/zone.dart:1136:13)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#46     _StreamController._add (dart:async/stream_controller.dart:640:7)
#47     _StreamController.add (dart:async/stream_controller.dart:586:5)
#48     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#49     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
"},"id":"42"}
```

**Comment by jakemac53** [comment]
@bkonyi does the vm allow setting multiple breakpoint and just silently do nothing or does it only allow them if the provided uri is different?

@devoncarew does this cause any user visible problems?

**Comment by devoncarew** [comment]
From testing, it looks like the VM does allow it.

> does this cause any user visible problems?

Yes - the error result from the 2nd call means that we think that location is invalid, and change the type of the breakpoint (which changes the display to the user) to an 'invalid' breakpoint:

<img width="191" alt="Screen Shot 2019-10-25 at 11 10 02 AM" src="https://user-images.githubusercontent.com/1269969/67593983-2c899280-f718-11e9-863b-c775701cf545.png">

<img width="203" alt="Screen Shot 2019-10-25 at 11 10 51 AM" src="https://user-images.githubusercontent.com/1269969/67593990-314e4680-f718-11e9-9e3f-beea47b9ee07.png">

**Comment by jakemac53** [comment]
Ok, it does feel like we are doing the correct thing here but in the name of replicating everything the vm does we can swallow these errors silently.

**Comment by jakemac53** [comment]
Longer term I do wonder if we are going to end up in a place where the vm changes their behavior for this type of thing and we end up having to change it back etc... but from a practical standpoint its easier for consumers to just mirror the behavior for now.

**Comment by devoncarew** [comment]
Here's the traffic I get back from the VM for same app:

```
==> {"jsonrpc":"2.0","id":"15","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/1091789525434991","scriptUri":"file:///Users/devoncarew/IdeaProjects/foo_flutter/lib/main.dart","line":9}}

==> {"jsonrpc":"2.0","id":"17","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/1091789525434991","scriptUri":"package:foo_flutter/main.dart","line":9}}

<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@472076935\/scripts\/package%3Afoo_flutter%2Fmain.dart\/16e04215f05","uri":"package:foo_flutter\/main.dart","_kind":"kernel"},"line":9}},"id":"15"}

<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@472076935\/scripts\/package%3Afoo_flutter%2Fmain.dart\/16e04215f05","uri":"package:foo_flutter\/main.dart","_kind":"kernel"},"line":9}},"id":"17"}
```

(with some stream notify events removed)

**Comment by devoncarew** [comment]
We could adjust our (IntelliJ's) behavior so that we ignore errors for the other n-1 vm breakpoints sent, if we have one vm breakpoint that succeeds.

**Comment by jakemac53** [comment]
Oh so you actually got a different breakpoint ID from the vm? That makes it more complicated - we will only have one JS breakpoint.

**Comment by devoncarew** [comment]
Here's a more complete vm log, w/ less editing on my part, for clarity:

```
==> {"jsonrpc":"2.0","id":"15","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/2580528123232855","scriptUri":"file:///Users/devoncarew/IdeaProjects/foo_flutter/lib/main.dart","line":9}}

==> {"jsonrpc":"2.0","id":"16","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/2580528123232855","scriptUri":"package:foo_flutter/main.dart","line":9}}

<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointAdded","isolate":{"type":"@Isolate","id":"isolates\/2580528123232855","name":"main","number":"2580528123232855"},"timestamp":1572028269695,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@472076935\/scripts\/package%3Afoo_flutter%2Fmain.dart\/16e042f97da","uri":"package:foo_flutter\/main.dart","_kind":"kernel"},"line":9}}}}}

<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@472076935\/scripts\/package%3Afoo_flutter%2Fmain.dart\/16e042f97da","uri":"package:foo_flutter\/main.dart","_kind":"kernel"},"line":9}},"id":"15"}

==> {"jsonrpc":"2.0","id":"17","method":"resume","params":{"isolateId":"isolates/2580528123232855"}}

<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@472076935\/scripts\/package%3Afoo_flutter%2Fmain.dart\/16e042f97da","uri":"package:foo_flutter\/main.dart","_kind":"kernel"},"line":9}},"id":"16"}

<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","id":"isolates\/2580528123232855","name":"main","number":"2580528123232855"},"timestamp":1572028271988}}}

<== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"17"}


<app runs>


<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointResolved","isolate":{"type":"@Isolate","id":"isolates\/2580528123232855","name":"main","number":"2580528123232855"},"timestamp":1572028272111,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@472076935\/scripts\/package%3Afoo_flutter%2Fmain.dart\/16e042f97da","uri":"package:foo_flutter\/main.dart","_kind":"kernel"},"tokenPos":224}}}}}
```

**Comment by devoncarew** [comment]
Lowering this in priority as I'm thinking of re-working IntelliJ breakpoint logic a bit; this may no longer be an issue for us.

**Comment by jakemac53** [comment]
It should be pretty easy for us to change the behavior so we can likely do it soon in any case.
