### ISSUE TITLE
"Invalid remote object id" when calling getObject for bools

### ISSUE THREAD

**Issue by DanTup** [dart-lang/webdev#789]
This seems similar to https://github.com/dart-lang/webdev/issues/773 but for bools. A boolean variable is returned with the ID `objects/bool-true`:

```js
"value": {
	"type": "@Instance",
	"id": "objects/bool-true",
	"kind": "Bool",
	"class": {
		"type": "@Class",
		"id": "classes|dart:core|Bool",
		"name": "Bool"
	},
	"valueAsString": "true",
	"valueAsStringIsTruncated": false
}
```

But calls to `getObject` with that ID fail:

```
==> {"id":"503","method":"getObject","params":{"isolateId":"1","objectId":"objects/bool-true"}}
```

```
{
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "
			WipError 1572: {code: -32000, message: Invalid remote object id}
			#0      AppInspector.jsCallFunctionOn (package:dwds/src/debugging/inspector.dart:183:9)
			<asynchronous suspension>
			#1      ClassMetaData.metaDataFor (package:dwds/src/debugging/metadata.dart:65:36)
			<asynchronous suspension>
			#2      InstanceHelper.instanceFor (package:dwds/src/debugging/instance.dart:52:40)
			<asynchronous suspension>
			#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:313:24)
			<asynchronous suspension>
			#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:311:19)
			#5      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
			<asynchronous suspension>
			#6      _rootRunUnary (dart:async/zone.dart:1132:38)
			#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
			#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
		"
	},
	"id": "503"
}
```

**Comment by DanTup** [comment]
Similar thing for numbers:

```
{"id":"529","method":"getObject","params":{"isolateId":"1","objectId":"objects/double-1.1"}}
{"id":"530","method":"getObject","params":{"isolateId":"1","objectId":"#StringInstanceRef#one-point-one"}}
```

These throw similar errors.

**Comment by DanTup** [comment]
To clarify what I'm doing here - I have code like this:

```dart
  final m = {
    DateTime(2005, 1, 1): "new-year-2005",
    true: true,
    1: "one",
    1.1: "one-point-one",
  };
```

When you expand `m` in the Variables window, we show an entry for each entry in the map:

![Screenshot 2019-10-29 at 5 18 53 pm](https://user-images.githubusercontent.com/1078012/67791940-37258e00-fa70-11e9-813a-fd021ed46f10.png)

Each entry can be expanded to show the key/value (to allow you to inspect the fields of them if they're objects), which means we call `getObject()` on them (looking now, I wonder if we could skip this for known simple types - though I guess since this works in the VM it should probably work here).

Currently those `getObject` calls throw, so you end up with this:

![Screenshot 2019-10-29 at 5 19 59 pm](https://user-images.githubusercontent.com/1078012/67792043-62a87880-fa70-11e9-9783-a29243371120.png)
