### ISSUE TITLE
'getObject(@Class)' request causes 'Invalid remote object id' error.

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/webdev#791]
Windows 10, Dart SDK 2.6.0-dev.8.2, stagehand 3.3.4, webdev 2.5.3 (activated today), Chrome 77.0.3865.120.

I'm trying to debug a sample web-angular application (created by stagehand) using IntelliJ IDEA webdev integration. 
- IDE runs `webdev daemon web:53322 --launch-app=web/index.html`
- `Debug service listening on ws://127.0.0.1:64188/_CZ313OOFPg=`, IDE connects to it
- IDE sets a breakpoint: 
```
{"jsonrpc":"2.0","id":"7","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///C:/dart_projects/angularsample/lib/src/todo_list/todo_list_component.dart","line":36}}
```
Response: 
```
{"jsonrpc":"2.0","result":{"type":"Breakpoint","id":"1","breakpointNumber":null,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","id":"122","uri":"package:angularsample/src/todo_list/todo_list_component.dart"},"tokenPos":1347}},"id":"7"}
```
- The app suspends on a breakpoint. IDE asks for stack:
```
{"jsonrpc":"2.0","id":"10","method":"getStack","params":{"isolateId":"1"}}
```
Response contains:
```
{"jsonrpc":"2.0","result":{"type":"Stack","frames":[{"type":"Frame","index":0,"code":{"type":"@Code","id":"1032","name":"add","kind":"Dart"},"location":{"type":"SourceLocation","script":{"type":"@Script","id":"122","uri":"package:angularsample/src/todo_list/todo_list_component.dart"},"tokenPos":1348},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","id":"{\"injectedScriptId\":1,\"id\":142}","kind":"PlainInstance","class":{"type":"@Class","id":"package:angularsample/src/todo_list/todo_list_component.dart:TodoListComponent","name":"TodoListComponent"},"valueAsStringIsTruncated":false},"declarationTokenPos":-1,"scopeStartTokenPos":null,"scopeEndTokenPos":null}],"kind":"Regular"}, ...
```
- From this response IDE takes `@Class` id and asks for details:
```
{"jsonrpc":"2.0","id":"13","method":"getObject","params":{"isolateId":"1","objectId":"package:angularsample/src/todo_list/todo_list_component.dart:TodoListComponent"}}
```

**Problem:** unexpected error in response:
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "WipError 42: {code: -32000, message: Invalid remote object id}
              #0      AppInspector.jsCallFunctionOn (package:dwds/src/debugging/inspector.dart:176:9)
              <asynchronous suspension>
              #1      ClassMetaData.metaDataFor (package:dwds/src/debugging/metadata.dart:64:36)
              <asynchronous suspension>
              #2      InstanceHelper.instanceFor (package:dwds/src/debugging/instance.dart:74:40)
              <asynchronous suspension>
              #3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:310:24)
              <asynchronous suspension>
              #4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:315:19)
              #5      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
              <asynchronous suspension>
              #6      _rootRunUnary (dart:async/zone.dart:1132:38)
              #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
              #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
              #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
              #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
              #11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
              #12     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
              #13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
              #14     _rootRunUnary (dart:async/zone.dart:1132:38)
              #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
              #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
              #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
              #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
              #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
              #20     _StreamController._add (dart:async/stream_controller.dart:640:7)
              #21     _StreamController.add (dart:async/stream_controller.dart:586:5)
              #22     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
              #23     _rootRunUnary (dart:async/zone.dart:1132:38)
              #24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
              #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
              #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
              #27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
              #28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
              #29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
              #30     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
              #31     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
              #32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
              #33     _rootRunUnary (dart:async/zone.dart:1132:38)
              #34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
              #35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
              #36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
              #37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
              #38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
              #39     _StreamController._add (dart:async/stream_controller.dart:640:7)
              #40     _StreamController.add (dart:async/stream_controller.dart:586:5)
              #41     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
              #42     _rootRunUnary (dart:async/zone.dart:1136:13)
              #43     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
              #44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
              #45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
              #46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
              #47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
              #48     _StreamController._add (dart:async/stream_controller.dart:640:7)
              #49     _StreamController.add (dart:async/stream_controller.dart:586:5)
              #50     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
              #51     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
              #52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
              #53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
              #54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
              #55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
    "
  },
  "id": "13"
} 
```
```

**Comment by grouma** [comment]
The provide error message contains the old format for class IDs which would indicate that this issue is stale. 

I believe https://github.com/dart-lang/webdev/pull/788 resolved this issue.
