### ISSUE TITLE
NPE when trying to populate the local variables view while paused at a breakpoint

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#795]
This is from IntelliJ; I see this exception when (I believe) trying to retrieve the local variables for a frame while stepping through a flutter web app. I can get more details if necessary if the exception below doesn't have enough data.

```
==> {"jsonrpc":"2.0","id":"191","method":"getObject","params":{"isolateId":"1","objectId":"classes|package:flutter/src/material/ink_well.dart|_InkResponseState<InkResponse>"}}
```

```
<== {"jsonrpc":"2.0","error":{"code":-32603,"message":"Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: TypeError: Cannot read property 'name' of undefined
    at <anonymous>:9:25
    at <anonymous>:43:7
    at _InkResponseState.new.[_handleTap] (http://localhost:58597/packages/flutter/material.ddc.js:146507:7)
    at http://localhost:58597/packages/flutter/material.ddc.js:146580:646
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:6903:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:11084:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:10935:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:10913:24)
    at arena.GestureArenaManager.new.sweep (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:9932:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:9283:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:9267:24)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:9244:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:9218:34)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:58597/packages/flutter/src/gestures/arena.ddc.js:9209:65)
    at _engine.PointerBinding.new.[_onPointerData] (http://localhost:58597/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:145312:9)
    at http://localhost:58597/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:145526:26
    at HTMLElement.<anonymous> (http://localhost:58597/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:145461:11)
      type: object
      value: null
      attempted JS eval: `    (function() {
         var sdkUtils = require('dart_sdk').dart;
            var library = sdkUtils.getLibrary('package:flutter/src/material/ink_well.dart');
            if (!library) throw 'cannot find library for package:flutter/src/material/ink_well.dart';
           
      var result = {};
      var clazz = library[\"_InkResponseState<InkResponse>\"];
      var descriptor = {
          'name': clazz.name,
          'dartName': sdkUtils.typeName(clazz)
        };
      // TODO(jakemac): static methods once ddc supports them
      var methods = sdkUtils.getMethods(clazz);
      var methodNames = methods ? Object.keys(methods) : [];
      descriptor['methods'] = {};
      for (var name of methodNames) {
        var method = methods[name];
        descriptor['methods'][name] = {
          // TODO(jakemac): how can we get actual const info?
          \"isConst\": false,
          \"isStatic\": false,
        }
      }
      // TODO(jakemac): static fields once ddc supports them
      var fields = sdkUtils.getFields(clazz);
      var fieldNames = fields ? Object.keys(fields) : [];
      descriptor['fields'] = {};
      for (var name of fieldNames) {
        var field = fields[name];
        var libraryUri = Object.getOwnPropertySymbols(fields[name][\"type\"])
        .find(x => x.description == \"libraryUri\");
        descriptor['fields'][name] = {
          // TODO(jakemac): how can we get actual const info?
          \"isConst\": false,
          \"isFinal\": field.isFinal,
          \"isStatic\": false,
          \"classRefName\": fields[name][\"type\"][\"name\"],
          \"classRefDartName\": sdkUtils.typeName(fields[name][\"type\"]),
          \"classRefLibraryId\" : field[\"type\"][libraryUri],
        }
      }
      return descriptor;
    })()
    `
    #0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:84:5)
    #1      ClassHelper._constructClass (package:dwds/src/debugging/classes.dart:112:5)
    <asynchronous suspension>
    #2      ClassHelper.forObjectId (package:dwds/src/debugging/classes.dart:60:19)
    <asynchronous suspension>
    #3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:308:35)
    <asynchronous suspension>
    #4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:311:19)
    #5      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
    <asynchronous suspension>
    #6      _rootRunUnary (dart:async/zone.dart:1132:38)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
    #11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
    #12     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
    #13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
    #14     _rootRunUnary (dart:async/zone.dart:1132:38)
    #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
    #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
    #20     _StreamController._add (dart:async/stream_controller.dart:640:7)
    #21     _StreamController.add (dart:async/stream_controller.dart:586:5)
    #22     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
    #23     _rootRunUnary (dart:async/zone.dart:1132:38)
    #24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
    #28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
    #29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
    #30     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
    #31     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
    #32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
    #33     _rootRunUnary (dart:async/zone.dart:1132:38)
    #34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
    #38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
    #39     _StreamController._add (dart:async/stream_controller.dart:640:7)
    #40     _StreamController.add (dart:async/stream_controller.dart:586:5)
    #41     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
    #42     _rootRunUnary (dart:async/zone.dart:1136:13)
    #43     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
    #47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
    #48     _StreamController._add (dart:async/stream_controller.dart:640:7)
    #49     _StreamController.add (dart:async/stream_controller.dart:586:5)
    #50     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
    #51     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
    #52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
    #55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
    "},"id":"191"}
```

**Comment by devoncarew** [comment]
It looks like `clazz` is null in the `clazz.name` expression above; clazz is calculated via `library[\"_InkResponseState<InkResponse>\"]`.

**Comment by devoncarew** [comment]
I'm seeing an exception very similar to this, even with the latest published package:dwds:

```
Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: TypeError: Cannot read property 'name' of undefined
    at <anonymous>:9:25
    at <anonymous>:43:7
    at _InkResponseState.new.[_handleTap] (http://localhost:53669/packages/flutter/material.ddc.js:147329:7)
    at http://localhost:53669/packages/flutter/material.ddc.js:147403:634
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:6906:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:11087:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:10938:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:10916:24)
    at arena.GestureArenaManager.new.sweep (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:9935:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:9286:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:9270:24)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:9247:14)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:9221:34)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:53669/packages/flutter/src/gestures/arena.ddc.js:9212:65)
    at _engine.PointerBinding.new.[_onPointerData] (http://localhost:53669/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:145345:9)
    at http://localhost:53669/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:145559:26
    at HTMLElement.<anonymous> (http://localhost:53669/packages/build_web_compilers/src/dev_compiler/dart_sdk.js:145494:11)
  type: object
  value: null
attempted JS eval: `    (function() {
         var sdkUtils = require('dart_sdk').dart;
   var library = sdkUtils.getLibrary('package:flutter/src/material/ink_well.dart');
   if (!library) throw 'cannot find library for package:flutter/src/material/ink_well.dart';
  
      var result = {};
      var clazz = library["_InkResponseState<InkResponse>"];
      var descriptor = {
          'name': clazz.name,
          'dartName': sdkUtils.typeName(clazz)
        };
      // TODO(jakemac): static methods once ddc supports them
      var methods = sdkUtils.getMethods(clazz);
      var methodNames = methods ? Object.keys(methods) : [];
      descriptor['methods'] = {};
      for (var name of methodNames) {
        var method = methods[name];
        descriptor['methods'][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isStatic": false,
        }
      }
      // TODO(jakemac): static fields once ddc supports them
      var fields = sdkUtils.getFields(clazz);
      var fieldNames = fields ? Object.keys(fields) : [];
      descriptor['fields'] = {};
      for (var name of fieldNames) {
        var field = fields[name];
        var libraryUri = Object.getOwnPropertySymbols(fields[name]["type"])
        .find(x => x.description == "libraryUri");
        descriptor['fields'][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isFinal": field.isFinal,
          "isStatic": false,
          "classRefName": fields[name]["type"]["name"],
          "classRefDartName": sdkUtils.typeName(fields[name]["type"]),
          "classRefLibraryId" : field["type"][libraryUri],
        }
      }
      return descriptor;
    })()
    `

#0      handleErrorIfPresent (package:dwds/src/utilities/shared.dart:84:5)
#1      ClassHelper._constructClass (package:dwds/src/debugging/classes.dart:112:5)
<asynchronous suspension>
#2      ClassHelper.forObjectId (package:dwds/src/debugging/classes.dart:60:19)
<asynchronous suspension>
#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:308:35)
<asynchronous suspension>
#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:311:19)
#5      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1027:51)
<asynchronous suspension>
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#12     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#31     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#39     _StreamController._add (dart:async/stream_controller.dart:640:7)
#40     _StreamController.add (dart:async/stream_controller.dart:586:5)
#41     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#42     _rootRunUnary (dart:async/zone.dart:1136:13)
#43     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#48     _StreamController._add (dart:async/stream_controller.dart:640:7)
#49     _StreamController.add (dart:async/stream_controller.dart:586:5)
#50     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#51     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by jakemac53** [comment]
The generic class looks like a likely culprit...

```
var clazz = library["_InkResponseState<InkResponse>"];
```

**Comment by devoncarew** [comment]
The expected view is something like this:

<img width="895" alt="Screen Shot 2019-11-04 at 10 43 40 AM" src="https://user-images.githubusercontent.com/1269969/68148031-1934af00-fef0-11e9-98e1-a0b8fd92dbb5.png">

But instead we see:

<img width="938" alt="Screen Shot 2019-11-04 at 10 43 51 AM" src="https://user-images.githubusercontent.com/1269969/68148019-12a63780-fef0-11e9-9d1e-ca4369a7bb89.png">

**Comment by devoncarew** [comment]
It looks like we may want to remove the generic portion of the name from this line:

https://github.com/dart-lang/webdev/pull/788/files#diff-001d6b5deea990dc8c213d16fc15ddb8R72

cc @grouma and @alan-knight as well

**Comment by grouma** [comment]
I can take a look at this. Do you have a small repo I can run this on?

**Comment by devoncarew** [comment]
Thanks!

> Do you have a small repo I can run this on?

Hmm, not a small one, no. What I've been doing is starting the std `flutter create` sample up and setting a breakpoint on the increment button callback. When it fires I've then hit step over 3-4 times until I get to a stack frame with this issue.

If you have a potential fix, I can try patching it in locally, setting up flutter tools w/ a dep override of package:dwds, and seeing if the issue still repros.
