### ISSUE TITLE
the evaluateInFrame unimplemented error return includes a stack trace

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#803]
A call to `evaluateInFrame` returns an error response currently; this is expected. However, the error response includes a stack trace. I'd expect to see that in the case of a server exception / fatal error in the server, but not as an expected error return. I'd expect to see something more like:

`{"jsonrpc":"2.0","error":{"code":<code>,"message":"UnimplementedError: evaluateInFrame is not yet implemented"}}`

This is a cosmetic issue - it's not surfaced to IDE users in any way.

---

```
==> {"jsonrpc":"2.0","id":"74","method":"evaluateInFrame","params":{"isolateId":"1","frameIndex":0,"expression":"_counter"}}

<== {"jsonrpc":"2.0","error":{"code":-32603,"message":"UnimplementedError
#0      ChromeProxyService.evaluateInFrame (package:dwds/src/services/chrome_proxy_service.dart:270:5)
#1      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:972:51)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#8      _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#16     _StreamController._add (dart:async/stream_controller.dart:640:7)
#17     _StreamController.add (dart:async/stream_controller.dart:586:5)
#18     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#27     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#28     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#35     _StreamController._add (dart:async/stream_controller.dart:640:7)
#36     _StreamController.add (dart:async/stream_controller.dart:586:5)
#37     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#38     _rootRunUnary (dart:async/zone.dart:1136:13)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#44     _StreamController._add (dart:async/stream_controller.dart:640:7)
#45     _StreamController.add (dart:async/stream_controller.dart:586:5)
#46     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#47     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
"},"id":"74"}
```

**Comment by grouma** [comment]
I don't think it's worth doing anything here. We throw as intended so the stack trace tags along. Given that this isn't surfaced to the user unless they do verbose printing it isn't an issue imo.
