### ISSUE TITLE
Version skew .. unhandled exception

### ISSUE THREAD

**Issue by drpond1** [dart-lang/webdev#864]
Working dir: /Users/user/Documents/dartProjects/drpond
/Users/userDocuments/dartProjects/dart/dart-sdk/bin/pub global run webdev build --output=web:build
[INFO] Current Version: 8Unhandled exception:
Instance of 'VersionSkew'
#0      _handleDaemonStartup (package:build_daemon/client.dart:84:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:57:26)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///Users/davidrosenthal/.pub-cache/hosted/pub.dartlang.org/webdev-2.5.1/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Process finished with exit code 255

**Comment by drpond1** [comment]
I fixed things.    I updated dart sdk first (just to be sure).
  Then I updated webdev dependencies in pubspec.yaml,  then I activated webdev,  then I  did pub get dependencies,  update, build.   Then did get,update, build again since it said something was out of date.     Then it ran.

**Comment by jakemac53** [comment]
We should be handling this error better - cc @grouma
