### ISSUE TITLE
Unhandled exception: Instance of 'MissingPortFile'

### ISSUE THREAD

**Issue by alfinbi** [dart-lang/webdev#913]
```
$ webdev serve
[INFO] Building new asset graph completed, took 1.6s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Unhandled exception:
Instance of 'MissingPortFile'
#0      _existingPort (package:build_daemon/client.dart:24:37)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:186:15)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:26:18)
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:194:24)
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:101:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)
#12     main (file:///opt/pub-cache/hosted/pub.dartlang.org/webdev-2.5.4/bin/webdev.dart:17:22)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

hi, I can't serve nor build web-angular with these errors, even after using ```stagehand web-angular```

**Comment by alfinbi** [comment]
solved after reinstalling dart. sorry for the inconvenience.

**Comment by alfinbi** [comment]
and now the error emerge again even after reinstalling dart

**Comment by sdxv** [comment]
I am getting the same error. I am in the midst of moving from Windows to Linux, so this was on a fresh install of everything (OS, IDE & Dart).

Here's how I got to the error.
clean new install of Fedora 31
install PHPStorm with Dart plugin
download Dart  2.7.1(ref 436881f) | Linux | x64 via zip file
run pub global activate webdev
in PHPStorm create a new project using the New Project wizard selecting Dart and "AngularDart Web App" as the boilerplate template.
once the project is open, make no changes and run webdev serve

see what happens:
```
[username@localhost dng-test]$ webdev serve
[INFO] Building new asset graph completed, took 1.9s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Unhandled exception:
Instance of 'MissingPortFile'
#0      _existingPort (package:build_daemon/client.dart:24:37)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:186:15)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:26:18)
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:194:24)
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:101:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)
#12     main (file:///home/username/.pub-cache/hosted/pub.dartlang.org/webdev-2.5.4/bin/webdev.dart:17:22)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[username@localhost dng-test]$ 
```

**Comment by bawachhe** [comment]
I'm also having this problem, exact same process and output..

Is there any information on why this is happening, or workarounds?

**Comment by bawachhe** [comment]
Actually, I found this conversation on [Gitter.im](https://gitter.im/dart-lang/angular)

> Alfin Bakhtiar Ilhami (@alfinbi) - Feb 29 12:41:
> has anyone suffered from error "Unhandled exception: Instance of 'MissingPortFile'" while running webdev serve?
> 
> ```$ webdev serve
> [INFO] Building new asset graph completed, took 1.6s
> [INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
> [INFO] Unhandled exception:
> Instance of 'MissingPortFile'
> #0      _existingPort (package:build_daemon/client.dart:24:37)
> <asynchronous suspension>
> #1      BuildDaemonClient.connect (package:build_daemon/client.dart:186:15)
> <asynchronous suspension>
> #2      connectClient (package:webdev/src/daemon_client.dart:17:23)
> #3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:26:18)
> #4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:194:24)
> #5      ServeCommand.run (package:webdev/src/command/serve_command.dart:101:27)
> <asynchronous suspension>
> #6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
> #7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
> #8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
> #9      new Future.sync (dart:async/future.dart:224:31)
> #10     CommandRunner.run (package:args/command_runner.dart:112:14)
> #11     run (package:webdev/src/webdev_command_runner.dart:19:56)
> #12     main (file:///opt/pub-cache/hosted/pub.dartlang.org/webdev-2.5.4/bin/webdev.dart:17:22)
> #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
> #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> ```
> 
> Andreas Mack (@andrm) - Feb 29 14:04:
> @alfinbi yes, happened to me a lot yesterday. Seems to be a problem when trying to connect to chrome
> I also see a few zombie processes from dart when this happens
> 
> Alfin Bakhtiar Ilhami (@alfinbi) - Feb 29 22:41:
> Any workaround?
> 
> Andreas Mack (@andrm) - Mar 01 15:21:
> @alfinbi I'm on Fedora and I have chrome-unstable running. What helped was to use webstorm and start webdev from there. It opened a "clean" chrome window (different profile). I'm going to try to go with chrome stable tomorrow
> 
> Alfin Bakhtiar Ilhami (@alfinbi) - Mar 01 20:54:
> @andrm I have no error if using pub run build_runner serve
> 
> Leonardo (@leonardoInf) - Mar 02 13:46:
> @alfinbi this happened to me after I ran a webdev build manually. I have set Chrome as my browser under build-configuration, restarted Webstorm and now it works.

I can confirm that using `pub run build_runner serve` works for a workaround.
