### ISSUE TITLE
StateError/Bad State crash in sse code from dwds/sse_handler

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/webdev#943]
We're seeing these crash reports from a subset of users running the very latest version of dwds.

```
Thread 0 main thread CRASHEDStateError: Bad state: StreamSink is closed

  | at _StreamSinkImpl.add | (io_sink.dart:156 )
-- | -- | --
  | at _Socket.add | (socket_patch.dart:1853 )
  | at _DetachedSocket.add | (http_impl.dart:3066 )
  | at _ByteAdapterSink.add | (byte_conversion.dart:60 )
  | at ByteConversionSinkBase.addSlice | (byte_conversion.dart:45 )
  | at _Utf8EncoderSink.addSlice | (utf.dart:267 )
  | at StringConversionSinkMixin.add | (string_conversion.dart:165 )
  | at SseConnection._setUpListener | (sse_handler.dart:73 )
  | at <asynchronous gap> | (async )
  | at new SseConnection | (sse_handler.dart:53 )
  | at SseHandler._createSseConnection.<anonymous closure> | (sse_handler.dart:161 )
  | at _fromHttpRequest.onHijack.<anonymous closure> | (shelf_io.dart:146 )
  | at _rootRunUnary | (zone.dart:1155 )
  | at _CustomZone.runUnary | (zone.dart:1048 )
  | at _FutureListener.handleValue | (future_impl.dart:141 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:556 )
  | at _rootRun | (zone.dart:1147 )
  | at _CustomZone.run | (zone.dart:1040 )
  | at _CustomZone.runGuarded | (zone.dart:942 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:982 )
  | at _microtaskLoop | (schedule_microtask.dart:43 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:52 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:118 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:169 )

```

**Comment by jonahwilliams** [comment]
fyi @grouma

**Comment by grouma** [comment]
Is there a little more detail?

**Comment by jonahwilliams** [comment]
Not much unfortunately, we know this is coming from an IDE:

`--no-color run --machine --track-widget-creation --device-id=chrome --start-paused lib/main.dart`

And this particular crash came from macOS

**Comment by jonahwilliams** [comment]
Its possible that the sse package needs to handle this error better so we get a clearer stack trace to figure out what is going on

**Comment by natebosch** [comment]
I think I've also seen `Bad state: StreamSink is closed` a few times recently. I haven't been able to narrow down a consistent repro, it has felt pretty random so far.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/sse/blame/a0ac454fac573bba5d8c38a11e52c8f68e416bc9/lib/src/server/sse_handler.dart#L83 seems suspect - this ends up closing the sink and the `_closeCompleter`, then we  immediately rerun the while loop which will result in this error.

**Comment by Agondev** [comment]
> I think I've also seen `Bad state: StreamSink is closed` a few times recently. I haven't been able to narrow down a consistent repro, it has felt pretty random so far.

I've had this happen 8 times so far in the span of a single day.

Here are the logs:

[flutter_01.log](https://github.com/dart-lang/webdev/files/4441029/flutter_01.log)
[flutter_02.log](https://github.com/dart-lang/webdev/files/4441030/flutter_02.log)
[flutter_03.log](https://github.com/dart-lang/webdev/files/4441031/flutter_03.log)
[flutter_04.log](https://github.com/dart-lang/webdev/files/4441032/flutter_04.log)
[flutter_05.log](https://github.com/dart-lang/webdev/files/4441033/flutter_05.log)
[flutter_06.log](https://github.com/dart-lang/webdev/files/4441034/flutter_06.log)
[flutter_07.log](https://github.com/dart-lang/webdev/files/4441035/flutter_07.log)
[flutter_08.log](https://github.com/dart-lang/webdev/files/4441036/flutter_08.log)

**Comment by jonahwilliams** [comment]
I don't believe the tool is using any keep alive logic, unless that is configured by dwds. @grouma would it be possible to tweak the line @jakemac53 to at least crash in a better way? We could pick up that change fairly quickly in flutter and that might reveal what else is going on.

This is also the biggest single crash in the tool right now, so I'm particular interested in a resolution :)

**Comment by grouma** [comment]
We do configure `keep-alive` by default [here](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/handlers/dev_handler.dart#L41).

I can get a PR out later today on `package:sse`.

**Comment by miyoyo** [comment]
I have gone trough the code line by line trying to figure out what happens, I know what doesn't happen, but I have absolutely no idea **why**. (Well, at least that's where my print based debugging brought me).

Sometimes, calls to _outgoingController.close() **will not fire any callbacks.** as an example, with *both* streamcontrollers being synchroneous, this code (Sorry about the mess, no debugger on hand):

```
  void _close() {
    print("[SSEC] _Closing $hashCode");
    if (!_closedCompleter.isCompleted) {
      print("[SSEC] _Closing $hashCode: closedcompleter is not complete");
      _closedCompleter.complete();
      print("[SSEC] Closing $hashCode: closedcompleter is now complete");
      _sink.close();
      print("[SSEC] Closing $hashCode: sink is closed");
      if (!_outgoingController.isClosed) {
        print("[SSEC] Closing $hashCode: out was not closed");
        _outgoingController.close();
        print("[SSEC] Closing $hashCode: out is closed");
      } else {
        print("[SSEC] Closing $hashCode: out was already closed!");
      }

      if (!_incomingController.isClosed) {
        print("[SSEC] Closing $hashCode: in was not closed");
        _incomingController.close();
        print("[SSEC] Closing $hashCode: in is closed");
      } else {
        print("[SSEC] Closing $hashCode: in was already closed!");
      }
      print("[SSEC] Closing $hashCode: sequence complete");
    } else {
      print("[SSEC] !!! Closing $hashCode: closedCompleter already complete!");
      print(StackTrace.current);
    }
  }
```

Can result in either

```
[SSEC] Closing 461433718
[SSEC] _Closing 461433718
[SSEC] _Closing 461433718: closedcompleter is not complete
[SSEC] Closing 461433718: closedcompleter is now complete
[SSEC] Closing 461433718: sink is closed
[SSEC] Closing 461433718: out was not closed
[SSEC] Closing 461433718: out is closed
[SSEC] Closing 461433718: in was not closed
[SSEC] _Closing 461433718
[SSEC] !!! Closing 461433718: closedCompleter already complete!
#0      SseConnection._close (package:sse/src/server/sse_handler.dart:157:24)
#1      _StreamController._recordCancel (dart:async/stream_controller.dart:715:20)        
#2      _ControllerSubscription._onCancel (dart:async/stream_controller.dart:843:24)      
#3      _BufferingStreamSubscription._cancel (dart:async/stream_impl.dart:244:21)
#4      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:395:5)        
#5      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#6      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)#7      _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)       
#8      _StreamController.close (dart:async/stream_controller.dart:624:5)
#9      SseConnection._close (package:sse/src/server/sse_handler.dart:149:29)
#10     SseConnection._handleDisconnect.<anonymous closure> (package:sse/src/server/sse_handler.dart:126:9)
#11     _rootRun (dart:async/zone.dart:1122:38)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23) 
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)        
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)  
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12) 

[SSEC] Closing 461433718: in is closed
[SSEC] Closing 461433718: sequence complete
```

or

```
[SSEC] Closing 174840985
[SSEC] _Closing 174840985
[SSEC] _Closing 174840985: closedcompleter is not complete
[SSEC] Closing 174840985: closedcompleter is now complete
[SSEC] Closing 174840985: sink is closed
[SSEC] Closing 174840985: out was not closed
[SSEC] _Closing 174840985
[SSEC] !!! Closing 174840985: closedCompleter already complete!
#0      SseConnection._close (package:sse/src/server/sse_handler.dart:157:24)
#1      _StreamController._recordCancel (dart:async/stream_controller.dart:715:20)        
#2      _ControllerSubscription._onCancel (dart:async/stream_controller.dart:843:24)      
#3      _BufferingStreamSubscription._cancel (dart:async/stream_impl.dart:244:21)
#4      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:395:5)        
#5      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#6      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)#7      _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)       
#8      _StreamController.close (dart:async/stream_controller.dart:624:5)
#9      SseConnection._close (package:sse/src/server/sse_handler.dart:141:29)
#10     SseConnection._handleDisconnect.<anonymous closure> (package:sse/src/server/sse_handler.dart:126:9)
#11     _rootRun (dart:async/zone.dart:1122:38)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23) 
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)        
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)  
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12) 

[SSEC] Closing 174840985: out is closed
[SSEC] Closing 174840985: in was not closed
[SSEC] _Closing 174840985
[SSEC] !!! Closing 174840985: closedCompleter already complete!
#0      SseConnection._close (package:sse/src/server/sse_handler.dart:157:24)
#1      _StreamController._recordCancel (dart:async/stream_controller.dart:715:20)        
#2      _ControllerSubscription._onCancel (dart:async/stream_controller.dart:843:24)      
#3      _BufferingStreamSubscription._cancel (dart:async/stream_impl.dart:244:21)
#4      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:395:5)        
#5      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#6      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)#7      _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)       
#8      _StreamController.close (dart:async/stream_controller.dart:624:5)
#9      SseConnection._close (package:sse/src/server/sse_handler.dart:149:29)
#10     SseConnection._handleDisconnect.<anonymous closure> (package:sse/src/server/sse_handler.dart:126:9)
#11     _rootRun (dart:async/zone.dart:1122:38)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23) 
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)        
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)  
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12) 

[SSEC] Closing 174840985: in is closed
[SSEC] Closing 174840985: sequence complete
[DWDS] Reaping dead SSE with: false : 174840985
```

In which case DWDS will reap the dead connection from it's list.

**Comment by grouma** [comment]
I believe this is now resolved as of https://github.com/dart-lang/sse/pull/26

Please re-open if you continue to run into issues.

**Comment by grouma** [comment]
Note that @jonahwilliams will still need to depend on the latest `package:sse` to resolve this in Flutter Tools. Webdev users will simply need to reactivate their latest global install so that the latest `package:sse` is pulled in.
