### ISSUE TITLE
unable to view variables when debugging a flutter web app in IntelliJ

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#965]
We get an exception when trying to populate the variables view:

<img width="982" alt="Screen Shot 2020-04-21 at 5 37 51 PM" src="https://user-images.githubusercontent.com/1269969/79928194-1c1c5100-83f7-11ea-9d6c-0abb590be0eb.png">

```
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ClassHelper._constructClass (package:dwds/src/debugging/classes.dart:72:58)
#2      ClassHelper.forObjectId (package:dwds/src/debugging/classes.dart:61:19)
<asynchronous suspension>
#3      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:316:35)
<asynchronous suspension>
#4      ChromeProxyService.getObject (package:dwds/src/services/chrome_proxy_service.dart:423:19)
#5      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1288:51)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#12     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#20     _StreamController._add (dart:async/stream_controller.dart:655:7)
#21     _StreamController.add (dart:async/stream_controller.dart:597:5)
#22     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#23     _rootRunUnary (dart:async/zone.dart:1192:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#30     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
#31     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#33     _rootRunUnary (dart:async/zone.dart:1192:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#39     _StreamController._add (dart:async/stream_controller.dart:655:7)
#40     _StreamController.add (dart:async/stream_controller.dart:597:5)
#41     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#42     _rootRunUnary (dart:async/zone.dart:1196:13)
#43     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#48     _StreamController._add (dart:async/stream_controller.dart:655:7)
#49     _StreamController.add (dart:async/stream_controller.dart:597:5)
#50     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#51     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by devoncarew** [comment]
This is something we should address - this means you essentially can't debug a flutter web app in IntelliJ.

**Comment by devoncarew** [comment]
cc @grouma

**Comment by grouma** [comment]
What's the workflow for using a custom version of `package:dwds` with Intellij?

**Comment by devoncarew** [comment]
> What's the workflow for using a custom version of `package:dwds` with Intellij?

Answered on another channel, but essentially add a local path dep in `//packages/flutter_tools/pubspec.yaml`, run pub get, and delete `//bin/cache/flutter_tools.stamp` to force the flutter tool to rebuild itself.

**Comment by annagrin** [comment]
Some addition, in case it might be helpful for debugging or workaround: 

I debugged this a bit during trying out expression evaluation, not sure what triggers it on the IDE side, maybe evaluating 'this' in the main scope?

Basically, the debugger is failing to find the libraryId because objectId parameter in the method below with the following callstack and parameters:

```
ClassHelper.forObjectId: "classes|null|NativeJavaScriptObject"
Inspector.getObject: "classes|null|NativeJavaScriptObject"
ChromeProxyService.getObject: "classes|null|NativeJavaScriptObject"
```

which causes `libraryId` on the following line to be `"null"`

https://github.com/dart-lang/webdev/blob/34f35f225d3bba7ec85912100d741294c5a3301d/dwds/lib/src/debugging/classes.dart#L58

I suspect that the same or similar issue causes the error in the variables window in VSCode:

![image](https://user-images.githubusercontent.com/12737689/80752469-6466fd80-8ae0-11ea-9412-01ff0815820a.png)

**Comment by annagrin** [comment]
Dug a little deeper on this. The problem is that we have a don't yet have a way to properly translate frames and scopes from Javascript to dart - the current translation is heuristic-based and largely relies on JavaScript code being close to dart code. In this particular case, we give 'this' as an available variable in the top main scope, which should not be there at all because it does not exist in dart.

VSCode seems to be getting the variables in a slightly different way from IntelliJ, so it is able to display 'this' but not its fields. 

Permanent solution will take some time as it will require information from the frontend server to have proper dart representation of frames and scopes in the debugger:

https://github.com/dart-lang/webdev/issues/982

For now, I will work on a temporary workaround (adjust of filtering of the scope) to unblock debugging in IntelliJ and make the 'this' variable disappear in VSCode.

**Comment by devoncarew** [comment]
Thanks for the investigation!

**Comment by annagrin** [comment]
@devoncarew published dwds and updated flutter (https://github.com/flutter/flutter/pull/56958)

**Comment by devoncarew** [comment]
Thanks!
