### ISSUE TITLE
support the VM service's `getSourceReport` method

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/webdev#970]
This is a request to support the VM service's `getSourceReport` method for package:dwds. Specifically, the 'PossibleBreakpoints' report kind (not the code coverage report). We use this call in DevTools in order to show which lines can support breakpoints (and show a visual indicator to that effect).

```
UnimplementedError
#0      ChromeProxyService.getSourceReport (package:dwds/src/services/chrome_proxy_service.dart:432:5)
#1      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1308:51)
...

 (-32603) from getSourceReport()
```

**Comment by devoncarew** [comment]
cc @grouma
