### ISSUE TITLE
got this issue while run flutter web app on chrome

### ISSUE THREAD

**Issue by anilgsharma900** [dart-lang/webdev#994]
```
Bad state: No serializer for 'DefaultBuildResult'.
Bad state: No serializer for 'DefaultBuildResult'.
    at Object.wrapException (http://localhost:38977/dwds/src/injected/client.js:987:17)
    at BuiltJsonSerializers._deserialize$3 (http://localhost:38977/dwds/src/injected/client.js:20246:19)
    at BuiltJsonSerializers.deserialize$2$specifiedType (http://localhost:38977/dwds/src/injected/client.js:20227:21)
    at BuiltJsonSerializers.deserialize$1 (http://localhost:38977/dwds/src/injected/client.js:20233:19)
    at http://localhost:38977/dwds/src/injected/client.js:23378:45
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:38977/dwds/src/injected/client.js:3516:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:38977/dwds/src/injected/client.js:11233:12)
    at Object._asyncStartSync (http://localhost:38977/dwds/src/injected/client.js:3480:20)
    at main__closure1.$call$body$main__closure (http://localhost:38977/dwds/src/injected/client.js:23433:16)
    at main__closure1.call$1 (http://localhost:38977/dwds/src/injected/client.js:23365:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:38977/dwds/src/injected/client.js:3818:16)
    at _CustomZone.runUnary$2$2 (http://localhost:38977/dwds/src/injected/client.js:12551:128)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:38977/dwds/src/injected/client.js:12479:14)
    at _ControllerSubscription._sendData$1 (http://localhost:38977/dwds/src/injected/client.js:12038:19)
    at _DelayedData.perform$1 (http://localhost:38977/dwds/src/injected/client.js:12192:62)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:38977/dwds/src/injected/client.js:12241:14)
    at Object._microtaskLoop (http://localhost:38977/dwds/src/injected/client.js:3681:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:38977/dwds/src/injected/client.js:3687:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:38977/dwds/src/injected/client.js:11108:9)
    at invokeClosure (http://localhost:38977/dwds/src/injected/client.js:1177:26)
    at MutationObserver.<anonymous> (http://localhost:38977/dwds/src/injected/client.js:1196:18)
```

**Comment by grouma** [comment]
@jonahwilliams this issue should no longer be relevant eh?

**Comment by jonahwilliams** [comment]
Yeah, this isn't used by the tooling at all
